/*
Waggle

Waggle API.

API version: 0.2.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SignupOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignupOutputBody{}

// SignupOutputBody struct for SignupOutputBody
type SignupOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema           *string   `json:"$schema,omitempty"`
	AccessExpiresAt  time.Time `json:"access_expires_at"`
	AccessToken      string    `json:"access_token"`
	AccountId        string    `json:"account_id"`
	Organization     OrgView   `json:"organization"`
	RefreshExpiresAt time.Time `json:"refresh_expires_at"`
	RefreshToken     string    `json:"refresh_token"`
}

type _SignupOutputBody SignupOutputBody

// NewSignupOutputBody instantiates a new SignupOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignupOutputBody(accessExpiresAt time.Time, accessToken string, accountId string, organization OrgView, refreshExpiresAt time.Time, refreshToken string) *SignupOutputBody {
	this := SignupOutputBody{}
	this.AccessExpiresAt = accessExpiresAt
	this.AccessToken = accessToken
	this.AccountId = accountId
	this.Organization = organization
	this.RefreshExpiresAt = refreshExpiresAt
	this.RefreshToken = refreshToken
	return &this
}

// NewSignupOutputBodyWithDefaults instantiates a new SignupOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignupOutputBodyWithDefaults() *SignupOutputBody {
	this := SignupOutputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *SignupOutputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignupOutputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *SignupOutputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *SignupOutputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetAccessExpiresAt returns the AccessExpiresAt field value
func (o *SignupOutputBody) GetAccessExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AccessExpiresAt
}

// GetAccessExpiresAtOk returns a tuple with the AccessExpiresAt field value
// and a boolean to check if the value has been set.
func (o *SignupOutputBody) GetAccessExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessExpiresAt, true
}

// SetAccessExpiresAt sets field value
func (o *SignupOutputBody) SetAccessExpiresAt(v time.Time) {
	o.AccessExpiresAt = v
}

// GetAccessToken returns the AccessToken field value
func (o *SignupOutputBody) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *SignupOutputBody) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *SignupOutputBody) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetAccountId returns the AccountId field value
func (o *SignupOutputBody) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *SignupOutputBody) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *SignupOutputBody) SetAccountId(v string) {
	o.AccountId = v
}

// GetOrganization returns the Organization field value
func (o *SignupOutputBody) GetOrganization() OrgView {
	if o == nil {
		var ret OrgView
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *SignupOutputBody) GetOrganizationOk() (*OrgView, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *SignupOutputBody) SetOrganization(v OrgView) {
	o.Organization = v
}

// GetRefreshExpiresAt returns the RefreshExpiresAt field value
func (o *SignupOutputBody) GetRefreshExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RefreshExpiresAt
}

// GetRefreshExpiresAtOk returns a tuple with the RefreshExpiresAt field value
// and a boolean to check if the value has been set.
func (o *SignupOutputBody) GetRefreshExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshExpiresAt, true
}

// SetRefreshExpiresAt sets field value
func (o *SignupOutputBody) SetRefreshExpiresAt(v time.Time) {
	o.RefreshExpiresAt = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *SignupOutputBody) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *SignupOutputBody) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *SignupOutputBody) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o SignupOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignupOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["access_expires_at"] = o.AccessExpiresAt
	toSerialize["access_token"] = o.AccessToken
	toSerialize["account_id"] = o.AccountId
	toSerialize["organization"] = o.Organization
	toSerialize["refresh_expires_at"] = o.RefreshExpiresAt
	toSerialize["refresh_token"] = o.RefreshToken
	return toSerialize, nil
}

func (o *SignupOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_expires_at",
		"access_token",
		"account_id",
		"organization",
		"refresh_expires_at",
		"refresh_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignupOutputBody := _SignupOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignupOutputBody)

	if err != nil {
		return err
	}

	*o = SignupOutputBody(varSignupOutputBody)

	return err
}

type NullableSignupOutputBody struct {
	value *SignupOutputBody
	isSet bool
}

func (v NullableSignupOutputBody) Get() *SignupOutputBody {
	return v.value
}

func (v *NullableSignupOutputBody) Set(val *SignupOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSignupOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSignupOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignupOutputBody(val *SignupOutputBody) *NullableSignupOutputBody {
	return &NullableSignupOutputBody{value: val, isSet: true}
}

func (v NullableSignupOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignupOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
