/*
Waggle

Waggle API.

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreatePoolInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePoolInputBody{}

// CreatePoolInputBody struct for CreatePoolInputBody
type CreatePoolInputBody struct {
	// A URL to the JSON Schema for this object.
	Schema       *string     `json:"$schema,omitempty"`
	DatacenterId string      `json:"datacenter_id"`
	DesiredCount int64       `json:"desired_count"`
	Metadata     interface{} `json:"metadata,omitempty"`
	Name         string      `json:"name"`
	SlotId       string      `json:"slot_id"`
}

type _CreatePoolInputBody CreatePoolInputBody

// NewCreatePoolInputBody instantiates a new CreatePoolInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePoolInputBody(datacenterId string, desiredCount int64, name string, slotId string) *CreatePoolInputBody {
	this := CreatePoolInputBody{}
	this.DatacenterId = datacenterId
	this.DesiredCount = desiredCount
	this.Name = name
	this.SlotId = slotId
	return &this
}

// NewCreatePoolInputBodyWithDefaults instantiates a new CreatePoolInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePoolInputBodyWithDefaults() *CreatePoolInputBody {
	this := CreatePoolInputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *CreatePoolInputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePoolInputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *CreatePoolInputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *CreatePoolInputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetDatacenterId returns the DatacenterId field value
func (o *CreatePoolInputBody) GetDatacenterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DatacenterId
}

// GetDatacenterIdOk returns a tuple with the DatacenterId field value
// and a boolean to check if the value has been set.
func (o *CreatePoolInputBody) GetDatacenterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DatacenterId, true
}

// SetDatacenterId sets field value
func (o *CreatePoolInputBody) SetDatacenterId(v string) {
	o.DatacenterId = v
}

// GetDesiredCount returns the DesiredCount field value
func (o *CreatePoolInputBody) GetDesiredCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DesiredCount
}

// GetDesiredCountOk returns a tuple with the DesiredCount field value
// and a boolean to check if the value has been set.
func (o *CreatePoolInputBody) GetDesiredCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DesiredCount, true
}

// SetDesiredCount sets field value
func (o *CreatePoolInputBody) SetDesiredCount(v int64) {
	o.DesiredCount = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatePoolInputBody) GetMetadata() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatePoolInputBody) GetMetadataOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreatePoolInputBody) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given interface{} and assigns it to the Metadata field.
func (o *CreatePoolInputBody) SetMetadata(v interface{}) {
	o.Metadata = v
}

// GetName returns the Name field value
func (o *CreatePoolInputBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreatePoolInputBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreatePoolInputBody) SetName(v string) {
	o.Name = v
}

// GetSlotId returns the SlotId field value
func (o *CreatePoolInputBody) GetSlotId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SlotId
}

// GetSlotIdOk returns a tuple with the SlotId field value
// and a boolean to check if the value has been set.
func (o *CreatePoolInputBody) GetSlotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SlotId, true
}

// SetSlotId sets field value
func (o *CreatePoolInputBody) SetSlotId(v string) {
	o.SlotId = v
}

func (o CreatePoolInputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePoolInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["datacenter_id"] = o.DatacenterId
	toSerialize["desired_count"] = o.DesiredCount
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["name"] = o.Name
	toSerialize["slot_id"] = o.SlotId
	return toSerialize, nil
}

func (o *CreatePoolInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"datacenter_id",
		"desired_count",
		"name",
		"slot_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePoolInputBody := _CreatePoolInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePoolInputBody)

	if err != nil {
		return err
	}

	*o = CreatePoolInputBody(varCreatePoolInputBody)

	return err
}

type NullableCreatePoolInputBody struct {
	value *CreatePoolInputBody
	isSet bool
}

func (v NullableCreatePoolInputBody) Get() *CreatePoolInputBody {
	return v.value
}

func (v *NullableCreatePoolInputBody) Set(val *CreatePoolInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePoolInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePoolInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePoolInputBody(val *CreatePoolInputBody) *NullableCreatePoolInputBody {
	return &NullableCreatePoolInputBody{value: val, isSet: true}
}

func (v NullableCreatePoolInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePoolInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
