/*
Waggle

Waggle API.

API version: 0.2.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MembershipView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MembershipView{}

// MembershipView struct for MembershipView
type MembershipView struct {
	OrganizationId   string `json:"organization_id"`
	OrganizationName string `json:"organization_name"`
	OrganizationSlug string `json:"organization_slug"`
}

type _MembershipView MembershipView

// NewMembershipView instantiates a new MembershipView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMembershipView(organizationId string, organizationName string, organizationSlug string) *MembershipView {
	this := MembershipView{}
	this.OrganizationId = organizationId
	this.OrganizationName = organizationName
	this.OrganizationSlug = organizationSlug
	return &this
}

// NewMembershipViewWithDefaults instantiates a new MembershipView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMembershipViewWithDefaults() *MembershipView {
	this := MembershipView{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *MembershipView) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *MembershipView) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *MembershipView) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetOrganizationName returns the OrganizationName field value
func (o *MembershipView) GetOrganizationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value
// and a boolean to check if the value has been set.
func (o *MembershipView) GetOrganizationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationName, true
}

// SetOrganizationName sets field value
func (o *MembershipView) SetOrganizationName(v string) {
	o.OrganizationName = v
}

// GetOrganizationSlug returns the OrganizationSlug field value
func (o *MembershipView) GetOrganizationSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationSlug
}

// GetOrganizationSlugOk returns a tuple with the OrganizationSlug field value
// and a boolean to check if the value has been set.
func (o *MembershipView) GetOrganizationSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationSlug, true
}

// SetOrganizationSlug sets field value
func (o *MembershipView) SetOrganizationSlug(v string) {
	o.OrganizationSlug = v
}

func (o MembershipView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MembershipView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["organization_name"] = o.OrganizationName
	toSerialize["organization_slug"] = o.OrganizationSlug
	return toSerialize, nil
}

func (o *MembershipView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization_id",
		"organization_name",
		"organization_slug",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMembershipView := _MembershipView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMembershipView)

	if err != nil {
		return err
	}

	*o = MembershipView(varMembershipView)

	return err
}

type NullableMembershipView struct {
	value *MembershipView
	isSet bool
}

func (v NullableMembershipView) Get() *MembershipView {
	return v.value
}

func (v *NullableMembershipView) Set(val *MembershipView) {
	v.value = val
	v.isSet = true
}

func (v NullableMembershipView) IsSet() bool {
	return v.isSet
}

func (v *NullableMembershipView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMembershipView(val *MembershipView) *NullableMembershipView {
	return &NullableMembershipView{value: val, isSet: true}
}

func (v NullableMembershipView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMembershipView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
