/*
Waggle

Waggle API.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SlotView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlotView{}

// SlotView struct for SlotView
type SlotView struct {
	// A URL to the JSON Schema for this object.
	Schema    *string   `json:"$schema,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	DiskGb    int64     `json:"disk_gb"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	RamGb     int64     `json:"ram_gb"`
	UpdatedAt time.Time `json:"updated_at"`
	Vcpu      int64     `json:"vcpu"`
}

type _SlotView SlotView

// NewSlotView instantiates a new SlotView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlotView(createdAt time.Time, diskGb int64, id string, name string, ramGb int64, updatedAt time.Time, vcpu int64) *SlotView {
	this := SlotView{}
	this.CreatedAt = createdAt
	this.DiskGb = diskGb
	this.Id = id
	this.Name = name
	this.RamGb = ramGb
	this.UpdatedAt = updatedAt
	this.Vcpu = vcpu
	return &this
}

// NewSlotViewWithDefaults instantiates a new SlotView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlotViewWithDefaults() *SlotView {
	this := SlotView{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *SlotView) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlotView) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *SlotView) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *SlotView) SetSchema(v string) {
	o.Schema = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SlotView) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SlotView) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SlotView) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDiskGb returns the DiskGb field value
func (o *SlotView) GetDiskGb() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DiskGb
}

// GetDiskGbOk returns a tuple with the DiskGb field value
// and a boolean to check if the value has been set.
func (o *SlotView) GetDiskGbOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskGb, true
}

// SetDiskGb sets field value
func (o *SlotView) SetDiskGb(v int64) {
	o.DiskGb = v
}

// GetId returns the Id field value
func (o *SlotView) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SlotView) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SlotView) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SlotView) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SlotView) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SlotView) SetName(v string) {
	o.Name = v
}

// GetRamGb returns the RamGb field value
func (o *SlotView) GetRamGb() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RamGb
}

// GetRamGbOk returns a tuple with the RamGb field value
// and a boolean to check if the value has been set.
func (o *SlotView) GetRamGbOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RamGb, true
}

// SetRamGb sets field value
func (o *SlotView) SetRamGb(v int64) {
	o.RamGb = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SlotView) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SlotView) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SlotView) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetVcpu returns the Vcpu field value
func (o *SlotView) GetVcpu() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Vcpu
}

// GetVcpuOk returns a tuple with the Vcpu field value
// and a boolean to check if the value has been set.
func (o *SlotView) GetVcpuOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vcpu, true
}

// SetVcpu sets field value
func (o *SlotView) SetVcpu(v int64) {
	o.Vcpu = v
}

func (o SlotView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlotView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["disk_gb"] = o.DiskGb
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["ram_gb"] = o.RamGb
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["vcpu"] = o.Vcpu
	return toSerialize, nil
}

func (o *SlotView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"disk_gb",
		"id",
		"name",
		"ram_gb",
		"updated_at",
		"vcpu",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSlotView := _SlotView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSlotView)

	if err != nil {
		return err
	}

	*o = SlotView(varSlotView)

	return err
}

type NullableSlotView struct {
	value *SlotView
	isSet bool
}

func (v NullableSlotView) Get() *SlotView {
	return v.value
}

func (v *NullableSlotView) Set(val *SlotView) {
	v.value = val
	v.isSet = true
}

func (v NullableSlotView) IsSet() bool {
	return v.isSet
}

func (v *NullableSlotView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlotView(val *SlotView) *NullableSlotView {
	return &NullableSlotView{value: val, isSet: true}
}

func (v NullableSlotView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlotView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
