/*
Waggle

Waggle API.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the PlacementView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlacementView{}

// PlacementView struct for PlacementView
type PlacementView struct {
	// A URL to the JSON Schema for this object.
	Schema         *string   `json:"$schema,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	HypervisorId   string    `json:"hypervisor_id"`
	HypervisorName string    `json:"hypervisor_name"`
	Id             string    `json:"id"`
	Vmid           *int64    `json:"vmid,omitempty"`
}

type _PlacementView PlacementView

// NewPlacementView instantiates a new PlacementView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlacementView(createdAt time.Time, hypervisorId string, hypervisorName string, id string) *PlacementView {
	this := PlacementView{}
	this.CreatedAt = createdAt
	this.HypervisorId = hypervisorId
	this.HypervisorName = hypervisorName
	this.Id = id
	return &this
}

// NewPlacementViewWithDefaults instantiates a new PlacementView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlacementViewWithDefaults() *PlacementView {
	this := PlacementView{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *PlacementView) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlacementView) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *PlacementView) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *PlacementView) SetSchema(v string) {
	o.Schema = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PlacementView) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PlacementView) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PlacementView) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetHypervisorId returns the HypervisorId field value
func (o *PlacementView) GetHypervisorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HypervisorId
}

// GetHypervisorIdOk returns a tuple with the HypervisorId field value
// and a boolean to check if the value has been set.
func (o *PlacementView) GetHypervisorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HypervisorId, true
}

// SetHypervisorId sets field value
func (o *PlacementView) SetHypervisorId(v string) {
	o.HypervisorId = v
}

// GetHypervisorName returns the HypervisorName field value
func (o *PlacementView) GetHypervisorName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HypervisorName
}

// GetHypervisorNameOk returns a tuple with the HypervisorName field value
// and a boolean to check if the value has been set.
func (o *PlacementView) GetHypervisorNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HypervisorName, true
}

// SetHypervisorName sets field value
func (o *PlacementView) SetHypervisorName(v string) {
	o.HypervisorName = v
}

// GetId returns the Id field value
func (o *PlacementView) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlacementView) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlacementView) SetId(v string) {
	o.Id = v
}

// GetVmid returns the Vmid field value if set, zero value otherwise.
func (o *PlacementView) GetVmid() int64 {
	if o == nil || IsNil(o.Vmid) {
		var ret int64
		return ret
	}
	return *o.Vmid
}

// GetVmidOk returns a tuple with the Vmid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlacementView) GetVmidOk() (*int64, bool) {
	if o == nil || IsNil(o.Vmid) {
		return nil, false
	}
	return o.Vmid, true
}

// HasVmid returns a boolean if a field has been set.
func (o *PlacementView) HasVmid() bool {
	if o != nil && !IsNil(o.Vmid) {
		return true
	}

	return false
}

// SetVmid gets a reference to the given int64 and assigns it to the Vmid field.
func (o *PlacementView) SetVmid(v int64) {
	o.Vmid = &v
}

func (o PlacementView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlacementView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["hypervisor_id"] = o.HypervisorId
	toSerialize["hypervisor_name"] = o.HypervisorName
	toSerialize["id"] = o.Id
	if !IsNil(o.Vmid) {
		toSerialize["vmid"] = o.Vmid
	}
	return toSerialize, nil
}

func (o *PlacementView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"hypervisor_id",
		"hypervisor_name",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlacementView := _PlacementView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlacementView)

	if err != nil {
		return err
	}

	*o = PlacementView(varPlacementView)

	return err
}

type NullablePlacementView struct {
	value *PlacementView
	isSet bool
}

func (v NullablePlacementView) Get() *PlacementView {
	return v.value
}

func (v *NullablePlacementView) Set(val *PlacementView) {
	v.value = val
	v.isSet = true
}

func (v NullablePlacementView) IsSet() bool {
	return v.isSet
}

func (v *NullablePlacementView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlacementView(val *PlacementView) *NullablePlacementView {
	return &NullablePlacementView{value: val, isSet: true}
}

func (v NullablePlacementView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlacementView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
