/*
Waggle

Waggle API.

API version: 0.2.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the MemberJSONView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberJSONView{}

// MemberJSONView struct for MemberJSONView
type MemberJSONView struct {
	// A URL to the JSON Schema for this object.
	Schema      *string    `json:"$schema,omitempty"`
	AccountId   string     `json:"account_id"`
	CreatedAt   time.Time  `json:"created_at"`
	DisplayName string     `json:"display_name"`
	Email       string     `json:"email"`
	IsActive    bool       `json:"is_active"`
	LastLoginAt *time.Time `json:"last_login_at,omitempty"`
	// Invited but hasn't accepted (no password set yet).
	Pending bool   `json:"pending"`
	Role    string `json:"role"`
	UserId  string `json:"user_id"`
}

type _MemberJSONView MemberJSONView

// NewMemberJSONView instantiates a new MemberJSONView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberJSONView(accountId string, createdAt time.Time, displayName string, email string, isActive bool, pending bool, role string, userId string) *MemberJSONView {
	this := MemberJSONView{}
	this.AccountId = accountId
	this.CreatedAt = createdAt
	this.DisplayName = displayName
	this.Email = email
	this.IsActive = isActive
	this.Pending = pending
	this.Role = role
	this.UserId = userId
	return &this
}

// NewMemberJSONViewWithDefaults instantiates a new MemberJSONView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberJSONViewWithDefaults() *MemberJSONView {
	this := MemberJSONView{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *MemberJSONView) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *MemberJSONView) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *MemberJSONView) SetSchema(v string) {
	o.Schema = &v
}

// GetAccountId returns the AccountId field value
func (o *MemberJSONView) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *MemberJSONView) SetAccountId(v string) {
	o.AccountId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *MemberJSONView) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *MemberJSONView) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDisplayName returns the DisplayName field value
func (o *MemberJSONView) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *MemberJSONView) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetEmail returns the Email field value
func (o *MemberJSONView) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *MemberJSONView) SetEmail(v string) {
	o.Email = v
}

// GetIsActive returns the IsActive field value
func (o *MemberJSONView) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *MemberJSONView) SetIsActive(v bool) {
	o.IsActive = v
}

// GetLastLoginAt returns the LastLoginAt field value if set, zero value otherwise.
func (o *MemberJSONView) GetLastLoginAt() time.Time {
	if o == nil || IsNil(o.LastLoginAt) {
		var ret time.Time
		return ret
	}
	return *o.LastLoginAt
}

// GetLastLoginAtOk returns a tuple with the LastLoginAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetLastLoginAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastLoginAt) {
		return nil, false
	}
	return o.LastLoginAt, true
}

// HasLastLoginAt returns a boolean if a field has been set.
func (o *MemberJSONView) HasLastLoginAt() bool {
	if o != nil && !IsNil(o.LastLoginAt) {
		return true
	}

	return false
}

// SetLastLoginAt gets a reference to the given time.Time and assigns it to the LastLoginAt field.
func (o *MemberJSONView) SetLastLoginAt(v time.Time) {
	o.LastLoginAt = &v
}

// GetPending returns the Pending field value
func (o *MemberJSONView) GetPending() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Pending
}

// GetPendingOk returns a tuple with the Pending field value
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetPendingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pending, true
}

// SetPending sets field value
func (o *MemberJSONView) SetPending(v bool) {
	o.Pending = v
}

// GetRole returns the Role field value
func (o *MemberJSONView) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *MemberJSONView) SetRole(v string) {
	o.Role = v
}

// GetUserId returns the UserId field value
func (o *MemberJSONView) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *MemberJSONView) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *MemberJSONView) SetUserId(v string) {
	o.UserId = v
}

func (o MemberJSONView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberJSONView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["account_id"] = o.AccountId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["display_name"] = o.DisplayName
	toSerialize["email"] = o.Email
	toSerialize["is_active"] = o.IsActive
	if !IsNil(o.LastLoginAt) {
		toSerialize["last_login_at"] = o.LastLoginAt
	}
	toSerialize["pending"] = o.Pending
	toSerialize["role"] = o.Role
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *MemberJSONView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"created_at",
		"display_name",
		"email",
		"is_active",
		"pending",
		"role",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberJSONView := _MemberJSONView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberJSONView)

	if err != nil {
		return err
	}

	*o = MemberJSONView(varMemberJSONView)

	return err
}

type NullableMemberJSONView struct {
	value *MemberJSONView
	isSet bool
}

func (v NullableMemberJSONView) Get() *MemberJSONView {
	return v.value
}

func (v *NullableMemberJSONView) Set(val *MemberJSONView) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberJSONView) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberJSONView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberJSONView(val *MemberJSONView) *NullableMemberJSONView {
	return &NullableMemberJSONView{value: val, isSet: true}
}

func (v NullableMemberJSONView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberJSONView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
