/*
Waggle

Waggle API.

API version: 0.2.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the DatacenterView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DatacenterView{}

// DatacenterView struct for DatacenterView
type DatacenterView struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// Default vCPU sold per physical core, stamped onto hypervisors as they are discovered here. 1.0 is no overcommit. Changing it does not re-rate existing hypervisors.
	CpuOvercommitRatio float64   `json:"cpu_overcommit_ratio"`
	CreatedAt          time.Time `json:"created_at"`
	// Whether a Proxmox API token is configured (the token itself is never returned).
	HasToken bool   `json:"has_token"`
	Id       string `json:"id"`
	// Whether TLS verification is disabled for this cluster (self-signed certs).
	InsecureSkipVerify bool      `json:"insecure_skip_verify"`
	Name               string    `json:"name"`
	UpdatedAt          time.Time `json:"updated_at"`
	Url                string    `json:"url"`
}

type _DatacenterView DatacenterView

// NewDatacenterView instantiates a new DatacenterView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDatacenterView(cpuOvercommitRatio float64, createdAt time.Time, hasToken bool, id string, insecureSkipVerify bool, name string, updatedAt time.Time, url string) *DatacenterView {
	this := DatacenterView{}
	this.CpuOvercommitRatio = cpuOvercommitRatio
	this.CreatedAt = createdAt
	this.HasToken = hasToken
	this.Id = id
	this.InsecureSkipVerify = insecureSkipVerify
	this.Name = name
	this.UpdatedAt = updatedAt
	this.Url = url
	return &this
}

// NewDatacenterViewWithDefaults instantiates a new DatacenterView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDatacenterViewWithDefaults() *DatacenterView {
	this := DatacenterView{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *DatacenterView) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *DatacenterView) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *DatacenterView) SetSchema(v string) {
	o.Schema = &v
}

// GetCpuOvercommitRatio returns the CpuOvercommitRatio field value
func (o *DatacenterView) GetCpuOvercommitRatio() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.CpuOvercommitRatio
}

// GetCpuOvercommitRatioOk returns a tuple with the CpuOvercommitRatio field value
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetCpuOvercommitRatioOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuOvercommitRatio, true
}

// SetCpuOvercommitRatio sets field value
func (o *DatacenterView) SetCpuOvercommitRatio(v float64) {
	o.CpuOvercommitRatio = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DatacenterView) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DatacenterView) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetHasToken returns the HasToken field value
func (o *DatacenterView) GetHasToken() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasToken
}

// GetHasTokenOk returns a tuple with the HasToken field value
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetHasTokenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasToken, true
}

// SetHasToken sets field value
func (o *DatacenterView) SetHasToken(v bool) {
	o.HasToken = v
}

// GetId returns the Id field value
func (o *DatacenterView) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DatacenterView) SetId(v string) {
	o.Id = v
}

// GetInsecureSkipVerify returns the InsecureSkipVerify field value
func (o *DatacenterView) GetInsecureSkipVerify() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InsecureSkipVerify
}

// GetInsecureSkipVerifyOk returns a tuple with the InsecureSkipVerify field value
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetInsecureSkipVerifyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InsecureSkipVerify, true
}

// SetInsecureSkipVerify sets field value
func (o *DatacenterView) SetInsecureSkipVerify(v bool) {
	o.InsecureSkipVerify = v
}

// GetName returns the Name field value
func (o *DatacenterView) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DatacenterView) SetName(v string) {
	o.Name = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DatacenterView) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DatacenterView) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
func (o *DatacenterView) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *DatacenterView) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *DatacenterView) SetUrl(v string) {
	o.Url = v
}

func (o DatacenterView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DatacenterView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["cpu_overcommit_ratio"] = o.CpuOvercommitRatio
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["has_token"] = o.HasToken
	toSerialize["id"] = o.Id
	toSerialize["insecure_skip_verify"] = o.InsecureSkipVerify
	toSerialize["name"] = o.Name
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *DatacenterView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cpu_overcommit_ratio",
		"created_at",
		"has_token",
		"id",
		"insecure_skip_verify",
		"name",
		"updated_at",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDatacenterView := _DatacenterView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDatacenterView)

	if err != nil {
		return err
	}

	*o = DatacenterView(varDatacenterView)

	return err
}

type NullableDatacenterView struct {
	value *DatacenterView
	isSet bool
}

func (v NullableDatacenterView) Get() *DatacenterView {
	return v.value
}

func (v *NullableDatacenterView) Set(val *DatacenterView) {
	v.value = val
	v.isSet = true
}

func (v NullableDatacenterView) IsSet() bool {
	return v.isSet
}

func (v *NullableDatacenterView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatacenterView(val *DatacenterView) *NullableDatacenterView {
	return &NullableDatacenterView{value: val, isSet: true}
}

func (v NullableDatacenterView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatacenterView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
