/*
Waggle

Waggle API.

API version: 0.2.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RefreshInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshInputBody{}

// RefreshInputBody struct for RefreshInputBody
type RefreshInputBody struct {
	// A URL to the JSON Schema for this object.
	Schema       *string `json:"$schema,omitempty"`
	RefreshToken string  `json:"refresh_token"`
}

type _RefreshInputBody RefreshInputBody

// NewRefreshInputBody instantiates a new RefreshInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshInputBody(refreshToken string) *RefreshInputBody {
	this := RefreshInputBody{}
	this.RefreshToken = refreshToken
	return &this
}

// NewRefreshInputBodyWithDefaults instantiates a new RefreshInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshInputBodyWithDefaults() *RefreshInputBody {
	this := RefreshInputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *RefreshInputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefreshInputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *RefreshInputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *RefreshInputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetRefreshToken returns the RefreshToken field value
func (o *RefreshInputBody) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *RefreshInputBody) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *RefreshInputBody) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o RefreshInputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["refresh_token"] = o.RefreshToken
	return toSerialize, nil
}

func (o *RefreshInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"refresh_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshInputBody := _RefreshInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshInputBody)

	if err != nil {
		return err
	}

	*o = RefreshInputBody(varRefreshInputBody)

	return err
}

type NullableRefreshInputBody struct {
	value *RefreshInputBody
	isSet bool
}

func (v NullableRefreshInputBody) Get() *RefreshInputBody {
	return v.value
}

func (v *NullableRefreshInputBody) Set(val *RefreshInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshInputBody(val *RefreshInputBody) *NullableRefreshInputBody {
	return &NullableRefreshInputBody{value: val, isSet: true}
}

func (v NullableRefreshInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
