/*
Waggle

Waggle API.

API version: 0.2.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HypervisorBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HypervisorBody{}

// HypervisorBody struct for HypervisorBody
type HypervisorBody struct {
	// A URL to the JSON Schema for this object.
	Schema             *string  `json:"$schema,omitempty"`
	CpuOvercommitRatio *float64 `json:"cpu_overcommit_ratio,omitempty"`
	CpuReserved        int64    `json:"cpu_reserved"`
	CpuTotal           int64    `json:"cpu_total"`
	DatacenterId       string   `json:"datacenter_id"`
	DiskGbReserved     int64    `json:"disk_gb_reserved"`
	DiskGbTotal        int64    `json:"disk_gb_total"`
	Name               string   `json:"name"`
	RamGbReserved      int64    `json:"ram_gb_reserved"`
	RamGbTotal         int64    `json:"ram_gb_total"`
	Schedulable        *bool    `json:"schedulable,omitempty"`
}

type _HypervisorBody HypervisorBody

// NewHypervisorBody instantiates a new HypervisorBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHypervisorBody(cpuReserved int64, cpuTotal int64, datacenterId string, diskGbReserved int64, diskGbTotal int64, name string, ramGbReserved int64, ramGbTotal int64) *HypervisorBody {
	this := HypervisorBody{}
	this.CpuReserved = cpuReserved
	this.CpuTotal = cpuTotal
	this.DatacenterId = datacenterId
	this.DiskGbReserved = diskGbReserved
	this.DiskGbTotal = diskGbTotal
	this.Name = name
	this.RamGbReserved = ramGbReserved
	this.RamGbTotal = ramGbTotal
	return &this
}

// NewHypervisorBodyWithDefaults instantiates a new HypervisorBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHypervisorBodyWithDefaults() *HypervisorBody {
	this := HypervisorBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *HypervisorBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *HypervisorBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *HypervisorBody) SetSchema(v string) {
	o.Schema = &v
}

// GetCpuOvercommitRatio returns the CpuOvercommitRatio field value if set, zero value otherwise.
func (o *HypervisorBody) GetCpuOvercommitRatio() float64 {
	if o == nil || IsNil(o.CpuOvercommitRatio) {
		var ret float64
		return ret
	}
	return *o.CpuOvercommitRatio
}

// GetCpuOvercommitRatioOk returns a tuple with the CpuOvercommitRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetCpuOvercommitRatioOk() (*float64, bool) {
	if o == nil || IsNil(o.CpuOvercommitRatio) {
		return nil, false
	}
	return o.CpuOvercommitRatio, true
}

// HasCpuOvercommitRatio returns a boolean if a field has been set.
func (o *HypervisorBody) HasCpuOvercommitRatio() bool {
	if o != nil && !IsNil(o.CpuOvercommitRatio) {
		return true
	}

	return false
}

// SetCpuOvercommitRatio gets a reference to the given float64 and assigns it to the CpuOvercommitRatio field.
func (o *HypervisorBody) SetCpuOvercommitRatio(v float64) {
	o.CpuOvercommitRatio = &v
}

// GetCpuReserved returns the CpuReserved field value
func (o *HypervisorBody) GetCpuReserved() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CpuReserved
}

// GetCpuReservedOk returns a tuple with the CpuReserved field value
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetCpuReservedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuReserved, true
}

// SetCpuReserved sets field value
func (o *HypervisorBody) SetCpuReserved(v int64) {
	o.CpuReserved = v
}

// GetCpuTotal returns the CpuTotal field value
func (o *HypervisorBody) GetCpuTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CpuTotal
}

// GetCpuTotalOk returns a tuple with the CpuTotal field value
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetCpuTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuTotal, true
}

// SetCpuTotal sets field value
func (o *HypervisorBody) SetCpuTotal(v int64) {
	o.CpuTotal = v
}

// GetDatacenterId returns the DatacenterId field value
func (o *HypervisorBody) GetDatacenterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DatacenterId
}

// GetDatacenterIdOk returns a tuple with the DatacenterId field value
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetDatacenterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DatacenterId, true
}

// SetDatacenterId sets field value
func (o *HypervisorBody) SetDatacenterId(v string) {
	o.DatacenterId = v
}

// GetDiskGbReserved returns the DiskGbReserved field value
func (o *HypervisorBody) GetDiskGbReserved() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DiskGbReserved
}

// GetDiskGbReservedOk returns a tuple with the DiskGbReserved field value
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetDiskGbReservedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskGbReserved, true
}

// SetDiskGbReserved sets field value
func (o *HypervisorBody) SetDiskGbReserved(v int64) {
	o.DiskGbReserved = v
}

// GetDiskGbTotal returns the DiskGbTotal field value
func (o *HypervisorBody) GetDiskGbTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DiskGbTotal
}

// GetDiskGbTotalOk returns a tuple with the DiskGbTotal field value
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetDiskGbTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskGbTotal, true
}

// SetDiskGbTotal sets field value
func (o *HypervisorBody) SetDiskGbTotal(v int64) {
	o.DiskGbTotal = v
}

// GetName returns the Name field value
func (o *HypervisorBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HypervisorBody) SetName(v string) {
	o.Name = v
}

// GetRamGbReserved returns the RamGbReserved field value
func (o *HypervisorBody) GetRamGbReserved() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RamGbReserved
}

// GetRamGbReservedOk returns a tuple with the RamGbReserved field value
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetRamGbReservedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RamGbReserved, true
}

// SetRamGbReserved sets field value
func (o *HypervisorBody) SetRamGbReserved(v int64) {
	o.RamGbReserved = v
}

// GetRamGbTotal returns the RamGbTotal field value
func (o *HypervisorBody) GetRamGbTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RamGbTotal
}

// GetRamGbTotalOk returns a tuple with the RamGbTotal field value
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetRamGbTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RamGbTotal, true
}

// SetRamGbTotal sets field value
func (o *HypervisorBody) SetRamGbTotal(v int64) {
	o.RamGbTotal = v
}

// GetSchedulable returns the Schedulable field value if set, zero value otherwise.
func (o *HypervisorBody) GetSchedulable() bool {
	if o == nil || IsNil(o.Schedulable) {
		var ret bool
		return ret
	}
	return *o.Schedulable
}

// GetSchedulableOk returns a tuple with the Schedulable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HypervisorBody) GetSchedulableOk() (*bool, bool) {
	if o == nil || IsNil(o.Schedulable) {
		return nil, false
	}
	return o.Schedulable, true
}

// HasSchedulable returns a boolean if a field has been set.
func (o *HypervisorBody) HasSchedulable() bool {
	if o != nil && !IsNil(o.Schedulable) {
		return true
	}

	return false
}

// SetSchedulable gets a reference to the given bool and assigns it to the Schedulable field.
func (o *HypervisorBody) SetSchedulable(v bool) {
	o.Schedulable = &v
}

func (o HypervisorBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HypervisorBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if !IsNil(o.CpuOvercommitRatio) {
		toSerialize["cpu_overcommit_ratio"] = o.CpuOvercommitRatio
	}
	toSerialize["cpu_reserved"] = o.CpuReserved
	toSerialize["cpu_total"] = o.CpuTotal
	toSerialize["datacenter_id"] = o.DatacenterId
	toSerialize["disk_gb_reserved"] = o.DiskGbReserved
	toSerialize["disk_gb_total"] = o.DiskGbTotal
	toSerialize["name"] = o.Name
	toSerialize["ram_gb_reserved"] = o.RamGbReserved
	toSerialize["ram_gb_total"] = o.RamGbTotal
	if !IsNil(o.Schedulable) {
		toSerialize["schedulable"] = o.Schedulable
	}
	return toSerialize, nil
}

func (o *HypervisorBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cpu_reserved",
		"cpu_total",
		"datacenter_id",
		"disk_gb_reserved",
		"disk_gb_total",
		"name",
		"ram_gb_reserved",
		"ram_gb_total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHypervisorBody := _HypervisorBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHypervisorBody)

	if err != nil {
		return err
	}

	*o = HypervisorBody(varHypervisorBody)

	return err
}

type NullableHypervisorBody struct {
	value *HypervisorBody
	isSet bool
}

func (v NullableHypervisorBody) Get() *HypervisorBody {
	return v.value
}

func (v *NullableHypervisorBody) Set(val *HypervisorBody) {
	v.value = val
	v.isSet = true
}

func (v NullableHypervisorBody) IsSet() bool {
	return v.isSet
}

func (v *NullableHypervisorBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHypervisorBody(val *HypervisorBody) *NullableHypervisorBody {
	return &NullableHypervisorBody{value: val, isSet: true}
}

func (v NullableHypervisorBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHypervisorBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
