/*
Waggle

Waggle API.

API version: 0.2.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RefreshOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshOutputBody{}

// RefreshOutputBody struct for RefreshOutputBody
type RefreshOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema           *string   `json:"$schema,omitempty"`
	AccessExpiresAt  time.Time `json:"access_expires_at"`
	AccessToken      string    `json:"access_token"`
	RefreshExpiresAt time.Time `json:"refresh_expires_at"`
	RefreshToken     string    `json:"refresh_token"`
}

type _RefreshOutputBody RefreshOutputBody

// NewRefreshOutputBody instantiates a new RefreshOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshOutputBody(accessExpiresAt time.Time, accessToken string, refreshExpiresAt time.Time, refreshToken string) *RefreshOutputBody {
	this := RefreshOutputBody{}
	this.AccessExpiresAt = accessExpiresAt
	this.AccessToken = accessToken
	this.RefreshExpiresAt = refreshExpiresAt
	this.RefreshToken = refreshToken
	return &this
}

// NewRefreshOutputBodyWithDefaults instantiates a new RefreshOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshOutputBodyWithDefaults() *RefreshOutputBody {
	this := RefreshOutputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *RefreshOutputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefreshOutputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *RefreshOutputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *RefreshOutputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetAccessExpiresAt returns the AccessExpiresAt field value
func (o *RefreshOutputBody) GetAccessExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AccessExpiresAt
}

// GetAccessExpiresAtOk returns a tuple with the AccessExpiresAt field value
// and a boolean to check if the value has been set.
func (o *RefreshOutputBody) GetAccessExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessExpiresAt, true
}

// SetAccessExpiresAt sets field value
func (o *RefreshOutputBody) SetAccessExpiresAt(v time.Time) {
	o.AccessExpiresAt = v
}

// GetAccessToken returns the AccessToken field value
func (o *RefreshOutputBody) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *RefreshOutputBody) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *RefreshOutputBody) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshExpiresAt returns the RefreshExpiresAt field value
func (o *RefreshOutputBody) GetRefreshExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RefreshExpiresAt
}

// GetRefreshExpiresAtOk returns a tuple with the RefreshExpiresAt field value
// and a boolean to check if the value has been set.
func (o *RefreshOutputBody) GetRefreshExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshExpiresAt, true
}

// SetRefreshExpiresAt sets field value
func (o *RefreshOutputBody) SetRefreshExpiresAt(v time.Time) {
	o.RefreshExpiresAt = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *RefreshOutputBody) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *RefreshOutputBody) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *RefreshOutputBody) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o RefreshOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["access_expires_at"] = o.AccessExpiresAt
	toSerialize["access_token"] = o.AccessToken
	toSerialize["refresh_expires_at"] = o.RefreshExpiresAt
	toSerialize["refresh_token"] = o.RefreshToken
	return toSerialize, nil
}

func (o *RefreshOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_expires_at",
		"access_token",
		"refresh_expires_at",
		"refresh_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshOutputBody := _RefreshOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshOutputBody)

	if err != nil {
		return err
	}

	*o = RefreshOutputBody(varRefreshOutputBody)

	return err
}

type NullableRefreshOutputBody struct {
	value *RefreshOutputBody
	isSet bool
}

func (v NullableRefreshOutputBody) Get() *RefreshOutputBody {
	return v.value
}

func (v *NullableRefreshOutputBody) Set(val *RefreshOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshOutputBody(val *RefreshOutputBody) *NullableRefreshOutputBody {
	return &NullableRefreshOutputBody{value: val, isSet: true}
}

func (v NullableRefreshOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
