/*
Waggle

Waggle API.

API version: 0.2.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the OrgFullView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgFullView{}

// OrgFullView struct for OrgFullView
type OrgFullView struct {
	// A URL to the JSON Schema for this object.
	Schema    *string   `json:"$schema,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	Domain    *string   `json:"domain,omitempty"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	// The calling account's role in this organization.
	Role   string `json:"role"`
	Slug   string `json:"slug"`
	Status string `json:"status"`
}

type _OrgFullView OrgFullView

// NewOrgFullView instantiates a new OrgFullView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgFullView(createdAt time.Time, id string, name string, role string, slug string, status string) *OrgFullView {
	this := OrgFullView{}
	this.CreatedAt = createdAt
	this.Id = id
	this.Name = name
	this.Role = role
	this.Slug = slug
	this.Status = status
	return &this
}

// NewOrgFullViewWithDefaults instantiates a new OrgFullView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgFullViewWithDefaults() *OrgFullView {
	this := OrgFullView{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OrgFullView) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgFullView) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OrgFullView) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OrgFullView) SetSchema(v string) {
	o.Schema = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OrgFullView) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OrgFullView) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OrgFullView) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *OrgFullView) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgFullView) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *OrgFullView) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *OrgFullView) SetDomain(v string) {
	o.Domain = &v
}

// GetId returns the Id field value
func (o *OrgFullView) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrgFullView) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrgFullView) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *OrgFullView) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrgFullView) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrgFullView) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *OrgFullView) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *OrgFullView) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *OrgFullView) SetRole(v string) {
	o.Role = v
}

// GetSlug returns the Slug field value
func (o *OrgFullView) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *OrgFullView) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *OrgFullView) SetSlug(v string) {
	o.Slug = v
}

// GetStatus returns the Status field value
func (o *OrgFullView) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OrgFullView) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OrgFullView) SetStatus(v string) {
	o.Status = v
}

func (o OrgFullView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgFullView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["slug"] = o.Slug
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *OrgFullView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"id",
		"name",
		"role",
		"slug",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrgFullView := _OrgFullView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrgFullView)

	if err != nil {
		return err
	}

	*o = OrgFullView(varOrgFullView)

	return err
}

type NullableOrgFullView struct {
	value *OrgFullView
	isSet bool
}

func (v NullableOrgFullView) Get() *OrgFullView {
	return v.value
}

func (v *NullableOrgFullView) Set(val *OrgFullView) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgFullView) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgFullView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgFullView(val *OrgFullView) *NullableOrgFullView {
	return &NullableOrgFullView{value: val, isSet: true}
}

func (v NullableOrgFullView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgFullView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
