/*
Waggle

Waggle API.

API version: 0.2.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OrgView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgView{}

// OrgView struct for OrgView
type OrgView struct {
	Id     string `json:"id"`
	Slug   string `json:"slug"`
	Status string `json:"status"`
}

type _OrgView OrgView

// NewOrgView instantiates a new OrgView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgView(id string, slug string, status string) *OrgView {
	this := OrgView{}
	this.Id = id
	this.Slug = slug
	this.Status = status
	return &this
}

// NewOrgViewWithDefaults instantiates a new OrgView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgViewWithDefaults() *OrgView {
	this := OrgView{}
	return &this
}

// GetId returns the Id field value
func (o *OrgView) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrgView) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrgView) SetId(v string) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *OrgView) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *OrgView) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *OrgView) SetSlug(v string) {
	o.Slug = v
}

// GetStatus returns the Status field value
func (o *OrgView) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OrgView) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OrgView) SetStatus(v string) {
	o.Status = v
}

func (o OrgView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *OrgView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrgView := _OrgView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrgView)

	if err != nil {
		return err
	}

	*o = OrgView(varOrgView)

	return err
}

type NullableOrgView struct {
	value *OrgView
	isSet bool
}

func (v NullableOrgView) Get() *OrgView {
	return v.value
}

func (v *NullableOrgView) Set(val *OrgView) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgView) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgView(val *OrgView) *NullableOrgView {
	return &NullableOrgView{value: val, isSet: true}
}

func (v NullableOrgView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
