/*
Waggle

Waggle API.

API version: 0.2.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"encoding/json"
)

// checks if the LoginOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginOutputBody{}

// LoginOutputBody struct for LoginOutputBody
type LoginOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema       *string          `json:"$schema,omitempty"`
	AccountId    *string          `json:"account_id,omitempty"`
	Memberships  []MembershipView `json:"memberships,omitempty"`
	Organization *OrgView         `json:"organization,omitempty"`
	Tokens       *AuthTokens      `json:"tokens,omitempty"`
}

// NewLoginOutputBody instantiates a new LoginOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginOutputBody() *LoginOutputBody {
	this := LoginOutputBody{}
	return &this
}

// NewLoginOutputBodyWithDefaults instantiates a new LoginOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginOutputBodyWithDefaults() *LoginOutputBody {
	this := LoginOutputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *LoginOutputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginOutputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *LoginOutputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *LoginOutputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *LoginOutputBody) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginOutputBody) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *LoginOutputBody) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *LoginOutputBody) SetAccountId(v string) {
	o.AccountId = &v
}

// GetMemberships returns the Memberships field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoginOutputBody) GetMemberships() []MembershipView {
	if o == nil {
		var ret []MembershipView
		return ret
	}
	return o.Memberships
}

// GetMembershipsOk returns a tuple with the Memberships field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoginOutputBody) GetMembershipsOk() ([]MembershipView, bool) {
	if o == nil || IsNil(o.Memberships) {
		return nil, false
	}
	return o.Memberships, true
}

// HasMemberships returns a boolean if a field has been set.
func (o *LoginOutputBody) HasMemberships() bool {
	if o != nil && !IsNil(o.Memberships) {
		return true
	}

	return false
}

// SetMemberships gets a reference to the given []MembershipView and assigns it to the Memberships field.
func (o *LoginOutputBody) SetMemberships(v []MembershipView) {
	o.Memberships = v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *LoginOutputBody) GetOrganization() OrgView {
	if o == nil || IsNil(o.Organization) {
		var ret OrgView
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginOutputBody) GetOrganizationOk() (*OrgView, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *LoginOutputBody) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given OrgView and assigns it to the Organization field.
func (o *LoginOutputBody) SetOrganization(v OrgView) {
	o.Organization = &v
}

// GetTokens returns the Tokens field value if set, zero value otherwise.
func (o *LoginOutputBody) GetTokens() AuthTokens {
	if o == nil || IsNil(o.Tokens) {
		var ret AuthTokens
		return ret
	}
	return *o.Tokens
}

// GetTokensOk returns a tuple with the Tokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginOutputBody) GetTokensOk() (*AuthTokens, bool) {
	if o == nil || IsNil(o.Tokens) {
		return nil, false
	}
	return o.Tokens, true
}

// HasTokens returns a boolean if a field has been set.
func (o *LoginOutputBody) HasTokens() bool {
	if o != nil && !IsNil(o.Tokens) {
		return true
	}

	return false
}

// SetTokens gets a reference to the given AuthTokens and assigns it to the Tokens field.
func (o *LoginOutputBody) SetTokens(v AuthTokens) {
	o.Tokens = &v
}

func (o LoginOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if o.Memberships != nil {
		toSerialize["memberships"] = o.Memberships
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Tokens) {
		toSerialize["tokens"] = o.Tokens
	}
	return toSerialize, nil
}

type NullableLoginOutputBody struct {
	value *LoginOutputBody
	isSet bool
}

func (v NullableLoginOutputBody) Get() *LoginOutputBody {
	return v.value
}

func (v *NullableLoginOutputBody) Set(val *LoginOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginOutputBody(val *LoginOutputBody) *NullableLoginOutputBody {
	return &NullableLoginOutputBody{value: val, isSet: true}
}

func (v NullableLoginOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
