/*
Waggle

Waggle API.

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DiscoverOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiscoverOutputBody{}

// DiscoverOutputBody struct for DiscoverOutputBody
type DiscoverOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string          `json:"$schema,omitempty"`
	Items  []HypervisorView `json:"items"`
	Queued bool             `json:"queued"`
}

type _DiscoverOutputBody DiscoverOutputBody

// NewDiscoverOutputBody instantiates a new DiscoverOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscoverOutputBody(items []HypervisorView, queued bool) *DiscoverOutputBody {
	this := DiscoverOutputBody{}
	this.Items = items
	this.Queued = queued
	return &this
}

// NewDiscoverOutputBodyWithDefaults instantiates a new DiscoverOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscoverOutputBodyWithDefaults() *DiscoverOutputBody {
	this := DiscoverOutputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *DiscoverOutputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoverOutputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *DiscoverOutputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *DiscoverOutputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetItems returns the Items field value
// If the value is explicit nil, the zero value for []HypervisorView will be returned
func (o *DiscoverOutputBody) GetItems() []HypervisorView {
	if o == nil {
		var ret []HypervisorView
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiscoverOutputBody) GetItemsOk() ([]HypervisorView, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *DiscoverOutputBody) SetItems(v []HypervisorView) {
	o.Items = v
}

// GetQueued returns the Queued field value
func (o *DiscoverOutputBody) GetQueued() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Queued
}

// GetQueuedOk returns a tuple with the Queued field value
// and a boolean to check if the value has been set.
func (o *DiscoverOutputBody) GetQueuedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Queued, true
}

// SetQueued sets field value
func (o *DiscoverOutputBody) SetQueued(v bool) {
	o.Queued = v
}

func (o DiscoverOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiscoverOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	toSerialize["queued"] = o.Queued
	return toSerialize, nil
}

func (o *DiscoverOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"queued",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiscoverOutputBody := _DiscoverOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiscoverOutputBody)

	if err != nil {
		return err
	}

	*o = DiscoverOutputBody(varDiscoverOutputBody)

	return err
}

type NullableDiscoverOutputBody struct {
	value *DiscoverOutputBody
	isSet bool
}

func (v NullableDiscoverOutputBody) Get() *DiscoverOutputBody {
	return v.value
}

func (v *NullableDiscoverOutputBody) Set(val *DiscoverOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoverOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoverOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoverOutputBody(val *DiscoverOutputBody) *NullableDiscoverOutputBody {
	return &NullableDiscoverOutputBody{value: val, isSet: true}
}

func (v NullableDiscoverOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoverOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
