/*
Waggle

Waggle API.

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PlacementListOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlacementListOutputBody{}

// PlacementListOutputBody struct for PlacementListOutputBody
type PlacementListOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string         `json:"$schema,omitempty"`
	Items  []PlacementView `json:"items"`
}

type _PlacementListOutputBody PlacementListOutputBody

// NewPlacementListOutputBody instantiates a new PlacementListOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlacementListOutputBody(items []PlacementView) *PlacementListOutputBody {
	this := PlacementListOutputBody{}
	this.Items = items
	return &this
}

// NewPlacementListOutputBodyWithDefaults instantiates a new PlacementListOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlacementListOutputBodyWithDefaults() *PlacementListOutputBody {
	this := PlacementListOutputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *PlacementListOutputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlacementListOutputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *PlacementListOutputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *PlacementListOutputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetItems returns the Items field value
// If the value is explicit nil, the zero value for []PlacementView will be returned
func (o *PlacementListOutputBody) GetItems() []PlacementView {
	if o == nil {
		var ret []PlacementView
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlacementListOutputBody) GetItemsOk() ([]PlacementView, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PlacementListOutputBody) SetItems(v []PlacementView) {
	o.Items = v
}

func (o PlacementListOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlacementListOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

func (o *PlacementListOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlacementListOutputBody := _PlacementListOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlacementListOutputBody)

	if err != nil {
		return err
	}

	*o = PlacementListOutputBody(varPlacementListOutputBody)

	return err
}

type NullablePlacementListOutputBody struct {
	value *PlacementListOutputBody
	isSet bool
}

func (v NullablePlacementListOutputBody) Get() *PlacementListOutputBody {
	return v.value
}

func (v *NullablePlacementListOutputBody) Set(val *PlacementListOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePlacementListOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePlacementListOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlacementListOutputBody(val *PlacementListOutputBody) *NullablePlacementListOutputBody {
	return &NullablePlacementListOutputBody{value: val, isSet: true}
}

func (v NullablePlacementListOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlacementListOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
