/*
Waggle

Waggle API.

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AuthTokens type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthTokens{}

// AuthTokens struct for AuthTokens
type AuthTokens struct {
	AccessExpiresAt  time.Time `json:"access_expires_at"`
	AccessToken      string    `json:"access_token"`
	RefreshExpiresAt time.Time `json:"refresh_expires_at"`
	RefreshToken     string    `json:"refresh_token"`
}

type _AuthTokens AuthTokens

// NewAuthTokens instantiates a new AuthTokens object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthTokens(accessExpiresAt time.Time, accessToken string, refreshExpiresAt time.Time, refreshToken string) *AuthTokens {
	this := AuthTokens{}
	this.AccessExpiresAt = accessExpiresAt
	this.AccessToken = accessToken
	this.RefreshExpiresAt = refreshExpiresAt
	this.RefreshToken = refreshToken
	return &this
}

// NewAuthTokensWithDefaults instantiates a new AuthTokens object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthTokensWithDefaults() *AuthTokens {
	this := AuthTokens{}
	return &this
}

// GetAccessExpiresAt returns the AccessExpiresAt field value
func (o *AuthTokens) GetAccessExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.AccessExpiresAt
}

// GetAccessExpiresAtOk returns a tuple with the AccessExpiresAt field value
// and a boolean to check if the value has been set.
func (o *AuthTokens) GetAccessExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessExpiresAt, true
}

// SetAccessExpiresAt sets field value
func (o *AuthTokens) SetAccessExpiresAt(v time.Time) {
	o.AccessExpiresAt = v
}

// GetAccessToken returns the AccessToken field value
func (o *AuthTokens) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *AuthTokens) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *AuthTokens) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshExpiresAt returns the RefreshExpiresAt field value
func (o *AuthTokens) GetRefreshExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RefreshExpiresAt
}

// GetRefreshExpiresAtOk returns a tuple with the RefreshExpiresAt field value
// and a boolean to check if the value has been set.
func (o *AuthTokens) GetRefreshExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshExpiresAt, true
}

// SetRefreshExpiresAt sets field value
func (o *AuthTokens) SetRefreshExpiresAt(v time.Time) {
	o.RefreshExpiresAt = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *AuthTokens) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *AuthTokens) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *AuthTokens) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o AuthTokens) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthTokens) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_expires_at"] = o.AccessExpiresAt
	toSerialize["access_token"] = o.AccessToken
	toSerialize["refresh_expires_at"] = o.RefreshExpiresAt
	toSerialize["refresh_token"] = o.RefreshToken
	return toSerialize, nil
}

func (o *AuthTokens) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_expires_at",
		"access_token",
		"refresh_expires_at",
		"refresh_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthTokens := _AuthTokens{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthTokens)

	if err != nil {
		return err
	}

	*o = AuthTokens(varAuthTokens)

	return err
}

type NullableAuthTokens struct {
	value *AuthTokens
	isSet bool
}

func (v NullableAuthTokens) Get() *AuthTokens {
	return v.value
}

func (v *NullableAuthTokens) Set(val *AuthTokens) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthTokens) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthTokens) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthTokens(val *AuthTokens) *NullableAuthTokens {
	return &NullableAuthTokens{value: val, isSet: true}
}

func (v NullableAuthTokens) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthTokens) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
