/*
Waggle

Waggle API.

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"encoding/json"
)

// checks if the DiscoverInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiscoverInputBody{}

// DiscoverInputBody struct for DiscoverInputBody
type DiscoverInputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Async  *bool   `json:"async,omitempty"`
}

// NewDiscoverInputBody instantiates a new DiscoverInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscoverInputBody() *DiscoverInputBody {
	this := DiscoverInputBody{}
	return &this
}

// NewDiscoverInputBodyWithDefaults instantiates a new DiscoverInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscoverInputBodyWithDefaults() *DiscoverInputBody {
	this := DiscoverInputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *DiscoverInputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoverInputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *DiscoverInputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *DiscoverInputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetAsync returns the Async field value if set, zero value otherwise.
func (o *DiscoverInputBody) GetAsync() bool {
	if o == nil || IsNil(o.Async) {
		var ret bool
		return ret
	}
	return *o.Async
}

// GetAsyncOk returns a tuple with the Async field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoverInputBody) GetAsyncOk() (*bool, bool) {
	if o == nil || IsNil(o.Async) {
		return nil, false
	}
	return o.Async, true
}

// HasAsync returns a boolean if a field has been set.
func (o *DiscoverInputBody) HasAsync() bool {
	if o != nil && !IsNil(o.Async) {
		return true
	}

	return false
}

// SetAsync gets a reference to the given bool and assigns it to the Async field.
func (o *DiscoverInputBody) SetAsync(v bool) {
	o.Async = &v
}

func (o DiscoverInputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiscoverInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if !IsNil(o.Async) {
		toSerialize["async"] = o.Async
	}
	return toSerialize, nil
}

type NullableDiscoverInputBody struct {
	value *DiscoverInputBody
	isSet bool
}

func (v NullableDiscoverInputBody) Get() *DiscoverInputBody {
	return v.value
}

func (v *NullableDiscoverInputBody) Set(val *DiscoverInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoverInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoverInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoverInputBody(val *DiscoverInputBody) *NullableDiscoverInputBody {
	return &NullableDiscoverInputBody{value: val, isSet: true}
}

func (v NullableDiscoverInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoverInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
