/*
Waggle

Waggle API.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VerifyEmailInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyEmailInputBody{}

// VerifyEmailInputBody struct for VerifyEmailInputBody
type VerifyEmailInputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Token  string  `json:"token"`
}

type _VerifyEmailInputBody VerifyEmailInputBody

// NewVerifyEmailInputBody instantiates a new VerifyEmailInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyEmailInputBody(token string) *VerifyEmailInputBody {
	this := VerifyEmailInputBody{}
	this.Token = token
	return &this
}

// NewVerifyEmailInputBodyWithDefaults instantiates a new VerifyEmailInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyEmailInputBodyWithDefaults() *VerifyEmailInputBody {
	this := VerifyEmailInputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *VerifyEmailInputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyEmailInputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *VerifyEmailInputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *VerifyEmailInputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetToken returns the Token field value
func (o *VerifyEmailInputBody) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *VerifyEmailInputBody) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *VerifyEmailInputBody) SetToken(v string) {
	o.Token = v
}

func (o VerifyEmailInputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyEmailInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *VerifyEmailInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyEmailInputBody := _VerifyEmailInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyEmailInputBody)

	if err != nil {
		return err
	}

	*o = VerifyEmailInputBody(varVerifyEmailInputBody)

	return err
}

type NullableVerifyEmailInputBody struct {
	value *VerifyEmailInputBody
	isSet bool
}

func (v NullableVerifyEmailInputBody) Get() *VerifyEmailInputBody {
	return v.value
}

func (v *NullableVerifyEmailInputBody) Set(val *VerifyEmailInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyEmailInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyEmailInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyEmailInputBody(val *VerifyEmailInputBody) *NullableVerifyEmailInputBody {
	return &NullableVerifyEmailInputBody{value: val, isSet: true}
}

func (v NullableVerifyEmailInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyEmailInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
