/*
Waggle

Waggle API.

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AddMemberInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddMemberInputBody{}

// AddMemberInputBody struct for AddMemberInputBody
type AddMemberInputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Email  string  `json:"email"`
	Role   *string `json:"role,omitempty"`
}

type _AddMemberInputBody AddMemberInputBody

// NewAddMemberInputBody instantiates a new AddMemberInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddMemberInputBody(email string) *AddMemberInputBody {
	this := AddMemberInputBody{}
	this.Email = email
	return &this
}

// NewAddMemberInputBodyWithDefaults instantiates a new AddMemberInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddMemberInputBodyWithDefaults() *AddMemberInputBody {
	this := AddMemberInputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *AddMemberInputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMemberInputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *AddMemberInputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *AddMemberInputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetEmail returns the Email field value
func (o *AddMemberInputBody) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AddMemberInputBody) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AddMemberInputBody) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AddMemberInputBody) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddMemberInputBody) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AddMemberInputBody) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AddMemberInputBody) SetRole(v string) {
	o.Role = &v
}

func (o AddMemberInputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddMemberInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["email"] = o.Email
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *AddMemberInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddMemberInputBody := _AddMemberInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddMemberInputBody)

	if err != nil {
		return err
	}

	*o = AddMemberInputBody(varAddMemberInputBody)

	return err
}

type NullableAddMemberInputBody struct {
	value *AddMemberInputBody
	isSet bool
}

func (v NullableAddMemberInputBody) Get() *AddMemberInputBody {
	return v.value
}

func (v *NullableAddMemberInputBody) Set(val *AddMemberInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAddMemberInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAddMemberInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddMemberInputBody(val *AddMemberInputBody) *NullableAddMemberInputBody {
	return &NullableAddMemberInputBody{value: val, isSet: true}
}

func (v NullableAddMemberInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddMemberInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
