/*
Waggle

Waggle API.

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AccountEmailView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountEmailView{}

// AccountEmailView struct for AccountEmailView
type AccountEmailView struct {
	Email      string     `json:"email"`
	Id         string     `json:"id"`
	IsPrimary  bool       `json:"is_primary"`
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
}

type _AccountEmailView AccountEmailView

// NewAccountEmailView instantiates a new AccountEmailView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountEmailView(email string, id string, isPrimary bool) *AccountEmailView {
	this := AccountEmailView{}
	this.Email = email
	this.Id = id
	this.IsPrimary = isPrimary
	return &this
}

// NewAccountEmailViewWithDefaults instantiates a new AccountEmailView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountEmailViewWithDefaults() *AccountEmailView {
	this := AccountEmailView{}
	return &this
}

// GetEmail returns the Email field value
func (o *AccountEmailView) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AccountEmailView) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AccountEmailView) SetEmail(v string) {
	o.Email = v
}

// GetId returns the Id field value
func (o *AccountEmailView) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccountEmailView) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccountEmailView) SetId(v string) {
	o.Id = v
}

// GetIsPrimary returns the IsPrimary field value
func (o *AccountEmailView) GetIsPrimary() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPrimary
}

// GetIsPrimaryOk returns a tuple with the IsPrimary field value
// and a boolean to check if the value has been set.
func (o *AccountEmailView) GetIsPrimaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPrimary, true
}

// SetIsPrimary sets field value
func (o *AccountEmailView) SetIsPrimary(v bool) {
	o.IsPrimary = v
}

// GetVerifiedAt returns the VerifiedAt field value if set, zero value otherwise.
func (o *AccountEmailView) GetVerifiedAt() time.Time {
	if o == nil || IsNil(o.VerifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.VerifiedAt
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountEmailView) GetVerifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.VerifiedAt) {
		return nil, false
	}
	return o.VerifiedAt, true
}

// HasVerifiedAt returns a boolean if a field has been set.
func (o *AccountEmailView) HasVerifiedAt() bool {
	if o != nil && !IsNil(o.VerifiedAt) {
		return true
	}

	return false
}

// SetVerifiedAt gets a reference to the given time.Time and assigns it to the VerifiedAt field.
func (o *AccountEmailView) SetVerifiedAt(v time.Time) {
	o.VerifiedAt = &v
}

func (o AccountEmailView) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountEmailView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["id"] = o.Id
	toSerialize["is_primary"] = o.IsPrimary
	if !IsNil(o.VerifiedAt) {
		toSerialize["verified_at"] = o.VerifiedAt
	}
	return toSerialize, nil
}

func (o *AccountEmailView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"id",
		"is_primary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountEmailView := _AccountEmailView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountEmailView)

	if err != nil {
		return err
	}

	*o = AccountEmailView(varAccountEmailView)

	return err
}

type NullableAccountEmailView struct {
	value *AccountEmailView
	isSet bool
}

func (v NullableAccountEmailView) Get() *AccountEmailView {
	return v.value
}

func (v *NullableAccountEmailView) Set(val *AccountEmailView) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountEmailView) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountEmailView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountEmailView(val *AccountEmailView) *NullableAccountEmailView {
	return &NullableAccountEmailView{value: val, isSet: true}
}

func (v NullableAccountEmailView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountEmailView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
