/*
Waggle

Waggle API.

API version: 0.2.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HealthOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthOutputBody{}

// HealthOutputBody struct for HealthOutputBody
type HealthOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Status string  `json:"status"`
}

type _HealthOutputBody HealthOutputBody

// NewHealthOutputBody instantiates a new HealthOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthOutputBody(status string) *HealthOutputBody {
	this := HealthOutputBody{}
	this.Status = status
	return &this
}

// NewHealthOutputBodyWithDefaults instantiates a new HealthOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthOutputBodyWithDefaults() *HealthOutputBody {
	this := HealthOutputBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *HealthOutputBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthOutputBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *HealthOutputBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *HealthOutputBody) SetSchema(v string) {
	o.Schema = &v
}

// GetStatus returns the Status field value
func (o *HealthOutputBody) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HealthOutputBody) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HealthOutputBody) SetStatus(v string) {
	o.Status = v
}

func (o HealthOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *HealthOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthOutputBody := _HealthOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthOutputBody)

	if err != nil {
		return err
	}

	*o = HealthOutputBody(varHealthOutputBody)

	return err
}

type NullableHealthOutputBody struct {
	value *HealthOutputBody
	isSet bool
}

func (v NullableHealthOutputBody) Get() *HealthOutputBody {
	return v.value
}

func (v *NullableHealthOutputBody) Set(val *HealthOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthOutputBody(val *HealthOutputBody) *NullableHealthOutputBody {
	return &NullableHealthOutputBody{value: val, isSet: true}
}

func (v NullableHealthOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
