/*
Waggle

Waggle API.

API version: 0.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waggle

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SlotBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlotBody{}

// SlotBody struct for SlotBody
type SlotBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	DiskGb int64   `json:"disk_gb"`
	Name   string  `json:"name"`
	RamGb  int64   `json:"ram_gb"`
	Vcpu   int64   `json:"vcpu"`
}

type _SlotBody SlotBody

// NewSlotBody instantiates a new SlotBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlotBody(diskGb int64, name string, ramGb int64, vcpu int64) *SlotBody {
	this := SlotBody{}
	this.DiskGb = diskGb
	this.Name = name
	this.RamGb = ramGb
	this.Vcpu = vcpu
	return &this
}

// NewSlotBodyWithDefaults instantiates a new SlotBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlotBodyWithDefaults() *SlotBody {
	this := SlotBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *SlotBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlotBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *SlotBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *SlotBody) SetSchema(v string) {
	o.Schema = &v
}

// GetDiskGb returns the DiskGb field value
func (o *SlotBody) GetDiskGb() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DiskGb
}

// GetDiskGbOk returns a tuple with the DiskGb field value
// and a boolean to check if the value has been set.
func (o *SlotBody) GetDiskGbOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskGb, true
}

// SetDiskGb sets field value
func (o *SlotBody) SetDiskGb(v int64) {
	o.DiskGb = v
}

// GetName returns the Name field value
func (o *SlotBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SlotBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SlotBody) SetName(v string) {
	o.Name = v
}

// GetRamGb returns the RamGb field value
func (o *SlotBody) GetRamGb() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RamGb
}

// GetRamGbOk returns a tuple with the RamGb field value
// and a boolean to check if the value has been set.
func (o *SlotBody) GetRamGbOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RamGb, true
}

// SetRamGb sets field value
func (o *SlotBody) SetRamGb(v int64) {
	o.RamGb = v
}

// GetVcpu returns the Vcpu field value
func (o *SlotBody) GetVcpu() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Vcpu
}

// GetVcpuOk returns a tuple with the Vcpu field value
// and a boolean to check if the value has been set.
func (o *SlotBody) GetVcpuOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vcpu, true
}

// SetVcpu sets field value
func (o *SlotBody) SetVcpu(v int64) {
	o.Vcpu = v
}

func (o SlotBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlotBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["disk_gb"] = o.DiskGb
	toSerialize["name"] = o.Name
	toSerialize["ram_gb"] = o.RamGb
	toSerialize["vcpu"] = o.Vcpu
	return toSerialize, nil
}

func (o *SlotBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"disk_gb",
		"name",
		"ram_gb",
		"vcpu",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSlotBody := _SlotBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSlotBody)

	if err != nil {
		return err
	}

	*o = SlotBody(varSlotBody)

	return err
}

type NullableSlotBody struct {
	value *SlotBody
	isSet bool
}

func (v NullableSlotBody) Get() *SlotBody {
	return v.value
}

func (v *NullableSlotBody) Set(val *SlotBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSlotBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSlotBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlotBody(val *SlotBody) *NullableSlotBody {
	return &NullableSlotBody{value: val, isSet: true}
}

func (v NullableSlotBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlotBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
