// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/glueops/terraform-provider-waggle/internal/client"
)

// OrganizationsModel is the Terraform model for organizations.
type OrganizationsModel struct {
	CreatedAt types.String `tfsdk:"created_at"`
	Domain    types.String `tfsdk:"domain"`
	Id        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	Role      types.String `tfsdk:"role"`
	Slug      types.String `tfsdk:"slug"`
	Status    types.String `tfsdk:"status"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *OrganizationsModel) ToClientModel() *client.OrgFullView {
	out := &client.OrgFullView{}
	if !m.CreatedAt.IsNull() && !m.CreatedAt.IsUnknown() {
		out.CreatedAt = m.CreatedAt.ValueString()
	}
	if !m.Domain.IsNull() && !m.Domain.IsUnknown() {
		out.Domain = m.Domain.ValueString()
	}
	if !m.Id.IsNull() && !m.Id.IsUnknown() {
		out.Id = m.Id.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Role.IsNull() && !m.Role.IsUnknown() {
		out.Role = m.Role.ValueString()
	}
	if !m.Slug.IsNull() && !m.Slug.IsUnknown() {
		out.Slug = m.Slug.ValueString()
	}
	if !m.Status.IsNull() && !m.Status.IsUnknown() {
		out.Status = m.Status.ValueString()
	}
	return out
}

// FromClientModel updates the Terraform model from a client model.
func (m *OrganizationsModel) FromClientModel(c *client.OrgFullView) {
	m.CreatedAt = types.StringValue(c.CreatedAt)
	m.Domain = types.StringValue(c.Domain)
	m.Id = types.StringValue(c.Id)
	m.Name = types.StringValue(c.Name)
	m.Role = types.StringValue(c.Role)
	m.Slug = types.StringValue(c.Slug)
	m.Status = types.StringValue(c.Status)
}
