// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/glueops/terraform-provider-waggle/internal/client"
)

var _ datasource.DataSource = &PlacementsDataSource{}

func NewPlacementsDataSource() datasource.DataSource {
	return &PlacementsDataSource{}
}

type PlacementsDataSource struct {
	client *client.Client
}

func (d *PlacementsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_placements"
}

func (d *PlacementsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a placements data source.",
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"hypervisor_id": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"hypervisor_name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"pool_id": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"vmid": schema.Int64Attribute{
				Computed:    true,
				Description: "",
			},
		},
	}
}

func (d *PlacementsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *PlacementsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config PlacementsModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/placements/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading placements", err.Error())
		return
	}

	var result client.PlacementView
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read placements data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
