/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberJSONView } from './MemberJSONView';
import {
    MemberJSONViewFromJSON,
    MemberJSONViewFromJSONTyped,
    MemberJSONViewToJSON,
    MemberJSONViewToJSONTyped,
} from './MemberJSONView';

/**
 * 
 * @export
 * @interface AddMemberOutputBody
 */
export interface AddMemberOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof AddMemberOutputBody
     */
    readonly $schema?: string;
    /**
     * An invite email was sent (pending account).
     * @type {boolean}
     * @memberof AddMemberOutputBody
     */
    invited: boolean;
    /**
     * 
     * @type {MemberJSONView}
     * @memberof AddMemberOutputBody
     */
    member: MemberJSONView;
}

/**
 * Check if a given object implements the AddMemberOutputBody interface.
 */
export function instanceOfAddMemberOutputBody(value: object): value is AddMemberOutputBody {
    if (!('invited' in value) || value['invited'] === undefined) return false;
    if (!('member' in value) || value['member'] === undefined) return false;
    return true;
}

export function AddMemberOutputBodyFromJSON(json: any): AddMemberOutputBody {
    return AddMemberOutputBodyFromJSONTyped(json, false);
}

export function AddMemberOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMemberOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'invited': json['invited'],
        'member': MemberJSONViewFromJSON(json['member']),
    };
}

export function AddMemberOutputBodyToJSON(json: any): AddMemberOutputBody {
    return AddMemberOutputBodyToJSONTyped(json, false);
}

export function AddMemberOutputBodyToJSONTyped(value?: Omit<AddMemberOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invited': value['invited'],
        'member': MemberJSONViewToJSON(value['member']),
    };
}

