/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrgInputBody
 */
export interface CreateOrgInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CreateOrgInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrgInputBody
     */
    name: string;
}

/**
 * Check if a given object implements the CreateOrgInputBody interface.
 */
export function instanceOfCreateOrgInputBody(value: object): value is CreateOrgInputBody {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateOrgInputBodyFromJSON(json: any): CreateOrgInputBody {
    return CreateOrgInputBodyFromJSONTyped(json, false);
}

export function CreateOrgInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrgInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'name': json['name'],
    };
}

export function CreateOrgInputBodyToJSON(json: any): CreateOrgInputBody {
    return CreateOrgInputBodyToJSONTyped(json, false);
}

export function CreateOrgInputBodyToJSONTyped(value?: Omit<CreateOrgInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

