/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAPIKeyInputBody
 */
export interface CreateAPIKeyInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CreateAPIKeyInputBody
     */
    readonly $schema?: string;
    /**
     * Days until the key expires; omit or 0 for no expiry.
     * @type {number}
     * @memberof CreateAPIKeyInputBody
     */
    expiresInDays?: number;
    /**
     * Human label for the key.
     * @type {string}
     * @memberof CreateAPIKeyInputBody
     */
    name: string;
}

/**
 * Check if a given object implements the CreateAPIKeyInputBody interface.
 */
export function instanceOfCreateAPIKeyInputBody(value: object): value is CreateAPIKeyInputBody {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateAPIKeyInputBodyFromJSON(json: any): CreateAPIKeyInputBody {
    return CreateAPIKeyInputBodyFromJSONTyped(json, false);
}

export function CreateAPIKeyInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAPIKeyInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'expiresInDays': json['expires_in_days'] == null ? undefined : json['expires_in_days'],
        'name': json['name'],
    };
}

export function CreateAPIKeyInputBodyToJSON(json: any): CreateAPIKeyInputBody {
    return CreateAPIKeyInputBodyToJSONTyped(json, false);
}

export function CreateAPIKeyInputBodyToJSONTyped(value?: Omit<CreateAPIKeyInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_in_days': value['expiresInDays'],
        'name': value['name'],
    };
}

