/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePoolInputBody
 */
export interface CreatePoolInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CreatePoolInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePoolInputBody
     */
    datacenterId: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePoolInputBody
     */
    desiredCount: number;
    /**
     * 
     * @type {any}
     * @memberof CreatePoolInputBody
     */
    metadata?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePoolInputBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePoolInputBody
     */
    slotId: string;
}

/**
 * Check if a given object implements the CreatePoolInputBody interface.
 */
export function instanceOfCreatePoolInputBody(value: object): value is CreatePoolInputBody {
    if (!('datacenterId' in value) || value['datacenterId'] === undefined) return false;
    if (!('desiredCount' in value) || value['desiredCount'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slotId' in value) || value['slotId'] === undefined) return false;
    return true;
}

export function CreatePoolInputBodyFromJSON(json: any): CreatePoolInputBody {
    return CreatePoolInputBodyFromJSONTyped(json, false);
}

export function CreatePoolInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePoolInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'datacenterId': json['datacenter_id'],
        'desiredCount': json['desired_count'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'],
        'slotId': json['slot_id'],
    };
}

export function CreatePoolInputBodyToJSON(json: any): CreatePoolInputBody {
    return CreatePoolInputBodyToJSONTyped(json, false);
}

export function CreatePoolInputBodyToJSONTyped(value?: Omit<CreatePoolInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datacenter_id': value['datacenterId'],
        'desired_count': value['desiredCount'],
        'metadata': value['metadata'],
        'name': value['name'],
        'slot_id': value['slotId'],
    };
}

