/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatacenterView } from './DatacenterView';
import {
    DatacenterViewFromJSON,
    DatacenterViewFromJSONTyped,
    DatacenterViewToJSON,
    DatacenterViewToJSONTyped,
} from './DatacenterView';

/**
 * 
 * @export
 * @interface DatacenterListOutputBody
 */
export interface DatacenterListOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DatacenterListOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<DatacenterView>}
     * @memberof DatacenterListOutputBody
     */
    items: Array<DatacenterView> | null;
}

/**
 * Check if a given object implements the DatacenterListOutputBody interface.
 */
export function instanceOfDatacenterListOutputBody(value: object): value is DatacenterListOutputBody {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function DatacenterListOutputBodyFromJSON(json: any): DatacenterListOutputBody {
    return DatacenterListOutputBodyFromJSONTyped(json, false);
}

export function DatacenterListOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatacenterListOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'items': (json['items'] == null ? null : (json['items'] as Array<any>).map(DatacenterViewFromJSON)),
    };
}

export function DatacenterListOutputBodyToJSON(json: any): DatacenterListOutputBody {
    return DatacenterListOutputBodyToJSONTyped(json, false);
}

export function DatacenterListOutputBodyToJSONTyped(value?: Omit<DatacenterListOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': (value['items'] == null ? null : (value['items'] as Array<any>).map(DatacenterViewToJSON)),
    };
}

