/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatacenterBody
 */
export interface DatacenterBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DatacenterBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof DatacenterBody
     */
    cpuOvercommitRatio?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DatacenterBody
     */
    insecureSkipVerify?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DatacenterBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DatacenterBody
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof DatacenterBody
     */
    url: string;
}

/**
 * Check if a given object implements the DatacenterBody interface.
 */
export function instanceOfDatacenterBody(value: object): value is DatacenterBody {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function DatacenterBodyFromJSON(json: any): DatacenterBody {
    return DatacenterBodyFromJSONTyped(json, false);
}

export function DatacenterBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatacenterBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'cpuOvercommitRatio': json['cpu_overcommit_ratio'] == null ? undefined : json['cpu_overcommit_ratio'],
        'insecureSkipVerify': json['insecure_skip_verify'] == null ? undefined : json['insecure_skip_verify'],
        'name': json['name'],
        'token': json['token'] == null ? undefined : json['token'],
        'url': json['url'],
    };
}

export function DatacenterBodyToJSON(json: any): DatacenterBody {
    return DatacenterBodyToJSONTyped(json, false);
}

export function DatacenterBodyToJSONTyped(value?: Omit<DatacenterBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu_overcommit_ratio': value['cpuOvercommitRatio'],
        'insecure_skip_verify': value['insecureSkipVerify'],
        'name': value['name'],
        'token': value['token'],
        'url': value['url'],
    };
}

