/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscoverInputBody
 */
export interface DiscoverInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DiscoverInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DiscoverInputBody
     */
    async?: boolean;
}

/**
 * Check if a given object implements the DiscoverInputBody interface.
 */
export function instanceOfDiscoverInputBody(value: object): value is DiscoverInputBody {
    return true;
}

export function DiscoverInputBodyFromJSON(json: any): DiscoverInputBody {
    return DiscoverInputBodyFromJSONTyped(json, false);
}

export function DiscoverInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscoverInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'async': json['async'] == null ? undefined : json['async'],
    };
}

export function DiscoverInputBodyToJSON(json: any): DiscoverInputBody {
    return DiscoverInputBodyToJSONTyped(json, false);
}

export function DiscoverInputBodyToJSONTyped(value?: Omit<DiscoverInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'async': value['async'],
    };
}

