/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FleetPlacementView } from './FleetPlacementView';
import {
    FleetPlacementViewFromJSON,
    FleetPlacementViewFromJSONTyped,
    FleetPlacementViewToJSON,
    FleetPlacementViewToJSONTyped,
} from './FleetPlacementView';

/**
 * 
 * @export
 * @interface FleetPlacementListOutputBody
 */
export interface FleetPlacementListOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof FleetPlacementListOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<FleetPlacementView>}
     * @memberof FleetPlacementListOutputBody
     */
    items: Array<FleetPlacementView> | null;
}

/**
 * Check if a given object implements the FleetPlacementListOutputBody interface.
 */
export function instanceOfFleetPlacementListOutputBody(value: object): value is FleetPlacementListOutputBody {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function FleetPlacementListOutputBodyFromJSON(json: any): FleetPlacementListOutputBody {
    return FleetPlacementListOutputBodyFromJSONTyped(json, false);
}

export function FleetPlacementListOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FleetPlacementListOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'items': (json['items'] == null ? null : (json['items'] as Array<any>).map(FleetPlacementViewFromJSON)),
    };
}

export function FleetPlacementListOutputBodyToJSON(json: any): FleetPlacementListOutputBody {
    return FleetPlacementListOutputBodyToJSONTyped(json, false);
}

export function FleetPlacementListOutputBodyToJSONTyped(value?: Omit<FleetPlacementListOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': (value['items'] == null ? null : (value['items'] as Array<any>).map(FleetPlacementViewToJSON)),
    };
}

