/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HypervisorView } from './HypervisorView';
import {
    HypervisorViewFromJSON,
    HypervisorViewFromJSONTyped,
    HypervisorViewToJSON,
    HypervisorViewToJSONTyped,
} from './HypervisorView';

/**
 * 
 * @export
 * @interface HypervisorListOutputBody
 */
export interface HypervisorListOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof HypervisorListOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<HypervisorView>}
     * @memberof HypervisorListOutputBody
     */
    items: Array<HypervisorView> | null;
}

/**
 * Check if a given object implements the HypervisorListOutputBody interface.
 */
export function instanceOfHypervisorListOutputBody(value: object): value is HypervisorListOutputBody {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function HypervisorListOutputBodyFromJSON(json: any): HypervisorListOutputBody {
    return HypervisorListOutputBodyFromJSONTyped(json, false);
}

export function HypervisorListOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HypervisorListOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'items': (json['items'] == null ? null : (json['items'] as Array<any>).map(HypervisorViewFromJSON)),
    };
}

export function HypervisorListOutputBodyToJSON(json: any): HypervisorListOutputBody {
    return HypervisorListOutputBodyToJSONTyped(json, false);
}

export function HypervisorListOutputBodyToJSONTyped(value?: Omit<HypervisorListOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': (value['items'] == null ? null : (value['items'] as Array<any>).map(HypervisorViewToJSON)),
    };
}

