/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HypervisorView
 */
export interface HypervisorView {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof HypervisorView
     */
    readonly $schema?: string;
    /**
     * cpu_effective_total minus reserved, existing-guest, and Waggle-committed vCPU.
     * @type {number}
     * @memberof HypervisorView
     */
    cpuBookable: number;
    /**
     * Schedulable vCPU pool: cpu_total x cpu_overcommit_ratio, rounded down.
     * @type {number}
     * @memberof HypervisorView
     */
    cpuEffectiveTotal: number;
    /**
     * vCPU sold per physical core on this node. 1.0 is no overcommit.
     * @type {number}
     * @memberof HypervisorView
     */
    cpuOvercommitRatio: number;
    /**
     * 
     * @type {number}
     * @memberof HypervisorView
     */
    cpuReserved: number;
    /**
     * Physical cores on the node.
     * @type {number}
     * @memberof HypervisorView
     */
    cpuTotal: number;
    /**
     * vCPU allocated to existing guests (from discovery).
     * @type {number}
     * @memberof HypervisorView
     */
    cpuUsed: number;
    /**
     * 
     * @type {Date}
     * @memberof HypervisorView
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof HypervisorView
     */
    datacenterId: string;
    /**
     * 
     * @type {number}
     * @memberof HypervisorView
     */
    diskGbBookable: number;
    /**
     * 
     * @type {number}
     * @memberof HypervisorView
     */
    diskGbReserved: number;
    /**
     * 
     * @type {number}
     * @memberof HypervisorView
     */
    diskGbTotal: number;
    /**
     * Disk (GB) allocated to existing guests (from discovery).
     * @type {number}
     * @memberof HypervisorView
     */
    diskGbUsed: number;
    /**
     * 
     * @type {string}
     * @memberof HypervisorView
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof HypervisorView
     */
    lastSyncedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof HypervisorView
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof HypervisorView
     */
    ramGbBookable: number;
    /**
     * 
     * @type {number}
     * @memberof HypervisorView
     */
    ramGbReserved: number;
    /**
     * 
     * @type {number}
     * @memberof HypervisorView
     */
    ramGbTotal: number;
    /**
     * RAM (GB) allocated to existing guests (from discovery).
     * @type {number}
     * @memberof HypervisorView
     */
    ramGbUsed: number;
    /**
     * When false, placement excludes this hypervisor.
     * @type {boolean}
     * @memberof HypervisorView
     */
    schedulable: boolean;
    /**
     * 
     * @type {Date}
     * @memberof HypervisorView
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the HypervisorView interface.
 */
export function instanceOfHypervisorView(value: object): value is HypervisorView {
    if (!('cpuBookable' in value) || value['cpuBookable'] === undefined) return false;
    if (!('cpuEffectiveTotal' in value) || value['cpuEffectiveTotal'] === undefined) return false;
    if (!('cpuOvercommitRatio' in value) || value['cpuOvercommitRatio'] === undefined) return false;
    if (!('cpuReserved' in value) || value['cpuReserved'] === undefined) return false;
    if (!('cpuTotal' in value) || value['cpuTotal'] === undefined) return false;
    if (!('cpuUsed' in value) || value['cpuUsed'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('datacenterId' in value) || value['datacenterId'] === undefined) return false;
    if (!('diskGbBookable' in value) || value['diskGbBookable'] === undefined) return false;
    if (!('diskGbReserved' in value) || value['diskGbReserved'] === undefined) return false;
    if (!('diskGbTotal' in value) || value['diskGbTotal'] === undefined) return false;
    if (!('diskGbUsed' in value) || value['diskGbUsed'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ramGbBookable' in value) || value['ramGbBookable'] === undefined) return false;
    if (!('ramGbReserved' in value) || value['ramGbReserved'] === undefined) return false;
    if (!('ramGbTotal' in value) || value['ramGbTotal'] === undefined) return false;
    if (!('ramGbUsed' in value) || value['ramGbUsed'] === undefined) return false;
    if (!('schedulable' in value) || value['schedulable'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function HypervisorViewFromJSON(json: any): HypervisorView {
    return HypervisorViewFromJSONTyped(json, false);
}

export function HypervisorViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): HypervisorView {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'cpuBookable': json['cpu_bookable'],
        'cpuEffectiveTotal': json['cpu_effective_total'],
        'cpuOvercommitRatio': json['cpu_overcommit_ratio'],
        'cpuReserved': json['cpu_reserved'],
        'cpuTotal': json['cpu_total'],
        'cpuUsed': json['cpu_used'],
        'createdAt': (new Date(json['created_at'])),
        'datacenterId': json['datacenter_id'],
        'diskGbBookable': json['disk_gb_bookable'],
        'diskGbReserved': json['disk_gb_reserved'],
        'diskGbTotal': json['disk_gb_total'],
        'diskGbUsed': json['disk_gb_used'],
        'id': json['id'],
        'lastSyncedAt': json['last_synced_at'] == null ? undefined : (new Date(json['last_synced_at'])),
        'name': json['name'],
        'ramGbBookable': json['ram_gb_bookable'],
        'ramGbReserved': json['ram_gb_reserved'],
        'ramGbTotal': json['ram_gb_total'],
        'ramGbUsed': json['ram_gb_used'],
        'schedulable': json['schedulable'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function HypervisorViewToJSON(json: any): HypervisorView {
    return HypervisorViewToJSONTyped(json, false);
}

export function HypervisorViewToJSONTyped(value?: Omit<HypervisorView, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu_bookable': value['cpuBookable'],
        'cpu_effective_total': value['cpuEffectiveTotal'],
        'cpu_overcommit_ratio': value['cpuOvercommitRatio'],
        'cpu_reserved': value['cpuReserved'],
        'cpu_total': value['cpuTotal'],
        'cpu_used': value['cpuUsed'],
        'created_at': value['createdAt'].toISOString(),
        'datacenter_id': value['datacenterId'],
        'disk_gb_bookable': value['diskGbBookable'],
        'disk_gb_reserved': value['diskGbReserved'],
        'disk_gb_total': value['diskGbTotal'],
        'disk_gb_used': value['diskGbUsed'],
        'id': value['id'],
        'last_synced_at': value['lastSyncedAt'] == null ? value['lastSyncedAt'] : value['lastSyncedAt'].toISOString(),
        'name': value['name'],
        'ram_gb_bookable': value['ramGbBookable'],
        'ram_gb_reserved': value['ramGbReserved'],
        'ram_gb_total': value['ramGbTotal'],
        'ram_gb_used': value['ramGbUsed'],
        'schedulable': value['schedulable'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

