/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthTokens } from './AuthTokens';
import {
    AuthTokensFromJSON,
    AuthTokensFromJSONTyped,
    AuthTokensToJSON,
    AuthTokensToJSONTyped,
} from './AuthTokens';
import type { OrgView } from './OrgView';
import {
    OrgViewFromJSON,
    OrgViewFromJSONTyped,
    OrgViewToJSON,
    OrgViewToJSONTyped,
} from './OrgView';
import type { MembershipView } from './MembershipView';
import {
    MembershipViewFromJSON,
    MembershipViewFromJSONTyped,
    MembershipViewToJSON,
    MembershipViewToJSONTyped,
} from './MembershipView';

/**
 * 
 * @export
 * @interface LoginOutputBody
 */
export interface LoginOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LoginOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginOutputBody
     */
    accountId?: string;
    /**
     * 
     * @type {Array<MembershipView>}
     * @memberof LoginOutputBody
     */
    memberships?: Array<MembershipView> | null;
    /**
     * 
     * @type {OrgView}
     * @memberof LoginOutputBody
     */
    organization?: OrgView;
    /**
     * 
     * @type {AuthTokens}
     * @memberof LoginOutputBody
     */
    tokens?: AuthTokens;
}

/**
 * Check if a given object implements the LoginOutputBody interface.
 */
export function instanceOfLoginOutputBody(value: object): value is LoginOutputBody {
    return true;
}

export function LoginOutputBodyFromJSON(json: any): LoginOutputBody {
    return LoginOutputBodyFromJSONTyped(json, false);
}

export function LoginOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'memberships': json['memberships'] == null ? undefined : ((json['memberships'] as Array<any>).map(MembershipViewFromJSON)),
        'organization': json['organization'] == null ? undefined : OrgViewFromJSON(json['organization']),
        'tokens': json['tokens'] == null ? undefined : AuthTokensFromJSON(json['tokens']),
    };
}

export function LoginOutputBodyToJSON(json: any): LoginOutputBody {
    return LoginOutputBodyToJSONTyped(json, false);
}

export function LoginOutputBodyToJSONTyped(value?: Omit<LoginOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'memberships': value['memberships'] == null ? undefined : ((value['memberships'] as Array<any>).map(MembershipViewToJSON)),
        'organization': OrgViewToJSON(value['organization']),
        'tokens': AuthTokensToJSON(value['tokens']),
    };
}

