/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrgView } from './OrgView';
import {
    OrgViewFromJSON,
    OrgViewFromJSONTyped,
    OrgViewToJSON,
    OrgViewToJSONTyped,
} from './OrgView';
import type { MembershipView } from './MembershipView';
import {
    MembershipViewFromJSON,
    MembershipViewFromJSONTyped,
    MembershipViewToJSON,
    MembershipViewToJSONTyped,
} from './MembershipView';
import type { AccountEmailView } from './AccountEmailView';
import {
    AccountEmailViewFromJSON,
    AccountEmailViewFromJSONTyped,
    AccountEmailViewToJSON,
    AccountEmailViewToJSONTyped,
} from './AccountEmailView';

/**
 * 
 * @export
 * @interface MeOutputBody
 */
export interface MeOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof MeOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof MeOutputBody
     */
    accountId: string;
    /**
     * 
     * @type {OrgView}
     * @memberof MeOutputBody
     */
    currentOrganization?: OrgView;
    /**
     * 
     * @type {string}
     * @memberof MeOutputBody
     */
    displayName: string;
    /**
     * 
     * @type {Array<AccountEmailView>}
     * @memberof MeOutputBody
     */
    emails: Array<AccountEmailView> | null;
    /**
     * 
     * @type {Date}
     * @memberof MeOutputBody
     */
    lastLoginAt?: Date;
    /**
     * 
     * @type {Array<MembershipView>}
     * @memberof MeOutputBody
     */
    memberships: Array<MembershipView> | null;
}

/**
 * Check if a given object implements the MeOutputBody interface.
 */
export function instanceOfMeOutputBody(value: object): value is MeOutputBody {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('emails' in value) || value['emails'] === undefined) return false;
    if (!('memberships' in value) || value['memberships'] === undefined) return false;
    return true;
}

export function MeOutputBodyFromJSON(json: any): MeOutputBody {
    return MeOutputBodyFromJSONTyped(json, false);
}

export function MeOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'accountId': json['account_id'],
        'currentOrganization': json['current_organization'] == null ? undefined : OrgViewFromJSON(json['current_organization']),
        'displayName': json['display_name'],
        'emails': (json['emails'] == null ? null : (json['emails'] as Array<any>).map(AccountEmailViewFromJSON)),
        'lastLoginAt': json['last_login_at'] == null ? undefined : (new Date(json['last_login_at'])),
        'memberships': (json['memberships'] == null ? null : (json['memberships'] as Array<any>).map(MembershipViewFromJSON)),
    };
}

export function MeOutputBodyToJSON(json: any): MeOutputBody {
    return MeOutputBodyToJSONTyped(json, false);
}

export function MeOutputBodyToJSONTyped(value?: Omit<MeOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'current_organization': OrgViewToJSON(value['currentOrganization']),
        'display_name': value['displayName'],
        'emails': (value['emails'] == null ? null : (value['emails'] as Array<any>).map(AccountEmailViewToJSON)),
        'last_login_at': value['lastLoginAt'] == null ? value['lastLoginAt'] : value['lastLoginAt'].toISOString(),
        'memberships': (value['memberships'] == null ? null : (value['memberships'] as Array<any>).map(MembershipViewToJSON)),
    };
}

