/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgView
 */
export interface OrgView {
    /**
     * 
     * @type {string}
     * @memberof OrgView
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrgView
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof OrgView
     */
    status: string;
}

/**
 * Check if a given object implements the OrgView interface.
 */
export function instanceOfOrgView(value: object): value is OrgView {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrgViewFromJSON(json: any): OrgView {
    return OrgViewFromJSONTyped(json, false);
}

export function OrgViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgView {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'status': json['status'],
    };
}

export function OrgViewToJSON(json: any): OrgView {
    return OrgViewToJSONTyped(json, false);
}

export function OrgViewToJSONTyped(value?: OrgView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'status': value['status'],
    };
}

