/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshOutputBody
 */
export interface RefreshOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof RefreshOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Date}
     * @memberof RefreshOutputBody
     */
    accessExpiresAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RefreshOutputBody
     */
    accessToken: string;
    /**
     * 
     * @type {Date}
     * @memberof RefreshOutputBody
     */
    refreshExpiresAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RefreshOutputBody
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshOutputBody interface.
 */
export function instanceOfRefreshOutputBody(value: object): value is RefreshOutputBody {
    if (!('accessExpiresAt' in value) || value['accessExpiresAt'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshExpiresAt' in value) || value['refreshExpiresAt'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function RefreshOutputBodyFromJSON(json: any): RefreshOutputBody {
    return RefreshOutputBodyFromJSONTyped(json, false);
}

export function RefreshOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'accessExpiresAt': (new Date(json['access_expires_at'])),
        'accessToken': json['access_token'],
        'refreshExpiresAt': (new Date(json['refresh_expires_at'])),
        'refreshToken': json['refresh_token'],
    };
}

export function RefreshOutputBodyToJSON(json: any): RefreshOutputBody {
    return RefreshOutputBodyToJSONTyped(json, false);
}

export function RefreshOutputBodyToJSONTyped(value?: Omit<RefreshOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_expires_at': value['accessExpiresAt'].toISOString(),
        'access_token': value['accessToken'],
        'refresh_expires_at': value['refreshExpiresAt'].toISOString(),
        'refresh_token': value['refreshToken'],
    };
}

