/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResizePoolInputBody
 */
export interface ResizePoolInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ResizePoolInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof ResizePoolInputBody
     */
    desiredCount: number;
}

/**
 * Check if a given object implements the ResizePoolInputBody interface.
 */
export function instanceOfResizePoolInputBody(value: object): value is ResizePoolInputBody {
    if (!('desiredCount' in value) || value['desiredCount'] === undefined) return false;
    return true;
}

export function ResizePoolInputBodyFromJSON(json: any): ResizePoolInputBody {
    return ResizePoolInputBodyFromJSONTyped(json, false);
}

export function ResizePoolInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResizePoolInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'desiredCount': json['desired_count'],
    };
}

export function ResizePoolInputBodyToJSON(json: any): ResizePoolInputBody {
    return ResizePoolInputBodyToJSONTyped(json, false);
}

export function ResizePoolInputBodyToJSONTyped(value?: Omit<ResizePoolInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'desired_count': value['desiredCount'],
    };
}

