/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupInputBody
 */
export interface SignupInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SignupInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupInputBody
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupInputBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupInputBody
     */
    organizationName: string;
    /**
     * 
     * @type {string}
     * @memberof SignupInputBody
     */
    password: string;
}

/**
 * Check if a given object implements the SignupInputBody interface.
 */
export function instanceOfSignupInputBody(value: object): value is SignupInputBody {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('organizationName' in value) || value['organizationName'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SignupInputBodyFromJSON(json: any): SignupInputBody {
    return SignupInputBodyFromJSONTyped(json, false);
}

export function SignupInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'email': json['email'],
        'organizationName': json['organization_name'],
        'password': json['password'],
    };
}

export function SignupInputBodyToJSON(json: any): SignupInputBody {
    return SignupInputBodyToJSONTyped(json, false);
}

export function SignupInputBodyToJSONTyped(value?: Omit<SignupInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'email': value['email'],
        'organization_name': value['organizationName'],
        'password': value['password'],
    };
}

