/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlotView
 */
export interface SlotView {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SlotView
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Date}
     * @memberof SlotView
     */
    createdAt: Date;
    /**
     * 
     * @type {number}
     * @memberof SlotView
     */
    diskGb: number;
    /**
     * 
     * @type {string}
     * @memberof SlotView
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SlotView
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SlotView
     */
    ramGb: number;
    /**
     * 
     * @type {Date}
     * @memberof SlotView
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof SlotView
     */
    vcpu: number;
}

/**
 * Check if a given object implements the SlotView interface.
 */
export function instanceOfSlotView(value: object): value is SlotView {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('diskGb' in value) || value['diskGb'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ramGb' in value) || value['ramGb'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('vcpu' in value) || value['vcpu'] === undefined) return false;
    return true;
}

export function SlotViewFromJSON(json: any): SlotView {
    return SlotViewFromJSONTyped(json, false);
}

export function SlotViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlotView {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'createdAt': (new Date(json['created_at'])),
        'diskGb': json['disk_gb'],
        'id': json['id'],
        'name': json['name'],
        'ramGb': json['ram_gb'],
        'updatedAt': (new Date(json['updated_at'])),
        'vcpu': json['vcpu'],
    };
}

export function SlotViewToJSON(json: any): SlotView {
    return SlotViewToJSONTyped(json, false);
}

export function SlotViewToJSONTyped(value?: Omit<SlotView, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'disk_gb': value['diskGb'],
        'id': value['id'],
        'name': value['name'],
        'ram_gb': value['ramGb'],
        'updated_at': value['updatedAt'].toISOString(),
        'vcpu': value['vcpu'],
    };
}

