/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlotBody
 */
export interface SlotBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SlotBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof SlotBody
     */
    diskGb: number;
    /**
     * 
     * @type {string}
     * @memberof SlotBody
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SlotBody
     */
    ramGb: number;
    /**
     * 
     * @type {number}
     * @memberof SlotBody
     */
    vcpu: number;
}

/**
 * Check if a given object implements the SlotBody interface.
 */
export function instanceOfSlotBody(value: object): value is SlotBody {
    if (!('diskGb' in value) || value['diskGb'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ramGb' in value) || value['ramGb'] === undefined) return false;
    if (!('vcpu' in value) || value['vcpu'] === undefined) return false;
    return true;
}

export function SlotBodyFromJSON(json: any): SlotBody {
    return SlotBodyFromJSONTyped(json, false);
}

export function SlotBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlotBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'diskGb': json['disk_gb'],
        'name': json['name'],
        'ramGb': json['ram_gb'],
        'vcpu': json['vcpu'],
    };
}

export function SlotBodyToJSON(json: any): SlotBody {
    return SlotBodyToJSONTyped(json, false);
}

export function SlotBodyToJSONTyped(value?: Omit<SlotBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disk_gb': value['diskGb'],
        'name': value['name'],
        'ram_gb': value['ramGb'],
        'vcpu': value['vcpu'],
    };
}

