/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMemberInputBody
 */
export interface UpdateMemberInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateMemberInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {UpdateMemberInputBodyRoleEnum}
     * @memberof UpdateMemberInputBody
     */
    role: UpdateMemberInputBodyRoleEnum;
}


/**
 * @export
 */
export const UpdateMemberInputBodyRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member'
} as const;
export type UpdateMemberInputBodyRoleEnum = typeof UpdateMemberInputBodyRoleEnum[keyof typeof UpdateMemberInputBodyRoleEnum];


/**
 * Check if a given object implements the UpdateMemberInputBody interface.
 */
export function instanceOfUpdateMemberInputBody(value: object): value is UpdateMemberInputBody {
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UpdateMemberInputBodyFromJSON(json: any): UpdateMemberInputBody {
    return UpdateMemberInputBodyFromJSONTyped(json, false);
}

export function UpdateMemberInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMemberInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'role': json['role'],
    };
}

export function UpdateMemberInputBodyToJSON(json: any): UpdateMemberInputBody {
    return UpdateMemberInputBodyToJSONTyped(json, false);
}

export function UpdateMemberInputBodyToJSONTyped(value?: Omit<UpdateMemberInputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
    };
}

