// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LogoutInputBody - LogoutInputBody struct
type LogoutInputBody struct {
	Schema string `json:"$schema,omitempty"`
	RefreshToken string `json:"refresh_token"`
}
