// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// MeOutputBody - MeOutputBody struct
type MeOutputBody struct {
	Schema string `json:"$schema,omitempty"`
	AccountId string `json:"account_id"`
	CurrentOrganization OrgView `json:"current_organization,omitempty"`
	DisplayName string `json:"display_name"`
	Emails []AccountEmailView `json:"emails"`
	LastLoginAt string `json:"last_login_at,omitempty"`
	Memberships []MembershipView `json:"memberships"`
}
