// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ResizePoolInputBody - ResizePoolInputBody struct
type ResizePoolInputBody struct {
	Schema string `json:"$schema,omitempty"`
	DesiredCount int64 `json:"desired_count"`
}
