// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HypervisorView - HypervisorView struct
type HypervisorView struct {
	Schema string `json:"$schema,omitempty"`
	CpuBookable int64 `json:"cpu_bookable"`
	CpuReserved int64 `json:"cpu_reserved"`
	CpuTotal int64 `json:"cpu_total"`
	CpuUsed int64 `json:"cpu_used"`
	CreatedAt string `json:"created_at"`
	DatacenterId string `json:"datacenter_id"`
	DiskGbBookable int64 `json:"disk_gb_bookable"`
	DiskGbReserved int64 `json:"disk_gb_reserved"`
	DiskGbTotal int64 `json:"disk_gb_total"`
	DiskGbUsed int64 `json:"disk_gb_used"`
	Id string `json:"id"`
	LastSyncedAt string `json:"last_synced_at,omitempty"`
	Name string `json:"name"`
	RamGbBookable int64 `json:"ram_gb_bookable"`
	RamGbReserved int64 `json:"ram_gb_reserved"`
	RamGbTotal int64 `json:"ram_gb_total"`
	RamGbUsed int64 `json:"ram_gb_used"`
	Schedulable bool `json:"schedulable"`
	UpdatedAt string `json:"updated_at"`
}
