// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AddMemberInputBody - AddMemberInputBody struct
type AddMemberInputBody struct {
	Schema string `json:"$schema,omitempty"`
	Email string `json:"email"`
	Role string `json:"role,omitempty"`
}
