// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// VersionOutputBody - VersionOutputBody struct
type VersionOutputBody struct {
	Schema string `json:"$schema,omitempty"`
	Commit string `json:"commit"`
	Date string `json:"date"`
	Version string `json:"version"`
}
