// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// FleetPlacementView - FleetPlacementView struct
type FleetPlacementView struct {
	CreatedAt string `json:"created_at"`
	DiskGb int64 `json:"disk_gb"`
	HypervisorId string `json:"hypervisor_id"`
	HypervisorName string `json:"hypervisor_name"`
	Id string `json:"id"`
	PoolId string `json:"pool_id"`
	PoolName string `json:"pool_name"`
	RamGb int64 `json:"ram_gb"`
	SlotName string `json:"slot_name"`
	Vcpu int64 `json:"vcpu"`
	Vmid int64 `json:"vmid,omitempty"`
}
