// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// OrgView - OrgView struct
type OrgView struct {
	Id string `json:"id"`
	Slug string `json:"slug"`
	Status string `json:"status"`
}
