// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HypervisorListOutputBody - HypervisorListOutputBody struct
type HypervisorListOutputBody struct {
	Schema string `json:"$schema,omitempty"`
	Items []HypervisorView `json:"items"`
}
