// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AccountEmailView - AccountEmailView struct
type AccountEmailView struct {
	Email string `json:"email"`
	Id string `json:"id"`
	IsPrimary bool `json:"is_primary"`
	VerifiedAt string `json:"verified_at,omitempty"`
}
