// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CreatePoolInputBody - CreatePoolInputBody struct
type CreatePoolInputBody struct {
	Schema string `json:"$schema,omitempty"`
	DatacenterId string `json:"datacenter_id"`
	DesiredCount int64 `json:"desired_count"`
	Metadata interface{} `json:"metadata,omitempty"`
	Name string `json:"name"`
	SlotId string `json:"slot_id"`
}
