// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PlacementListOutputBody - PlacementListOutputBody struct
type PlacementListOutputBody struct {
	Schema string `json:"$schema,omitempty"`
	Items []PlacementView `json:"items"`
}
