// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SignupOutputBody - SignupOutputBody struct
type SignupOutputBody struct {
	Schema string `json:"$schema,omitempty"`
	AccessExpiresAt string `json:"access_expires_at"`
	AccessToken string `json:"access_token"`
	AccountId string `json:"account_id"`
	Organization OrgView `json:"organization"`
	RefreshExpiresAt string `json:"refresh_expires_at"`
	RefreshToken string `json:"refresh_token"`
}
