// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LoginOutputBody - LoginOutputBody struct
type LoginOutputBody struct {
	Schema string `json:"$schema,omitempty"`
	AccountId string `json:"account_id,omitempty"`
	Memberships []MembershipView `json:"memberships,omitempty"`
	Organization OrgView `json:"organization,omitempty"`
	Tokens AuthTokens `json:"tokens,omitempty"`
}
