// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DiscoverInputBody - DiscoverInputBody struct
type DiscoverInputBody struct {
	Schema string `json:"$schema,omitempty"`
	Async bool `json:"async,omitempty"`
}
