// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// VerifyEmailInputBody - VerifyEmailInputBody struct
type VerifyEmailInputBody struct {
	Schema string `json:"$schema,omitempty"`
	Token string `json:"token"`
}
