// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// DatacenterBody - DatacenterBody struct
type DatacenterBody struct {
	Schema string `json:"$schema,omitempty"`
	InsecureSkipVerify bool `json:"insecure_skip_verify,omitempty"`
	Name string `json:"name"`
	Token string `json:"token,omitempty"`
	Url string `json:"url"`
}
