/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateAPIKeyInputBody,
    CreateAPIKeyInputBodyFromJSON,
    CreateAPIKeyInputBodyToJSON,
} from '../models/CreateAPIKeyInputBody';
import {
    type CreateAPIKeyOutputBody,
    CreateAPIKeyOutputBodyFromJSON,
    CreateAPIKeyOutputBodyToJSON,
} from '../models/CreateAPIKeyOutputBody';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';
import {
    type ListAPIKeysOutputBody,
    ListAPIKeysOutputBodyFromJSON,
    ListAPIKeysOutputBodyToJSON,
} from '../models/ListAPIKeysOutputBody';

export interface CreateApiKeyRequest {
    createAPIKeyInputBody: Omit<CreateAPIKeyInputBody, '$schema'>;
}

export interface RevokeApiKeyRequest {
    id: string;
}

/**
 * 
 */
export class ApiKeysApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiKey without sending the request
     */
    async createApiKeyRequestOpts(requestParameters: CreateApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createAPIKeyInputBody'] == null) {
            throw new runtime.RequiredError(
                'createAPIKeyInputBody',
                'Required parameter "createAPIKeyInputBody" was null or undefined when calling createApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api-keys`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAPIKeyInputBodyToJSON(requestParameters['createAPIKeyInputBody']),
        };
    }

    /**
     * Mint an organization API key for automation (e.g. Terraform). The plaintext token is returned once.
     */
    async createApiKeyRaw(requestParameters: CreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAPIKeyOutputBody>> {
        const requestOptions = await this.createApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAPIKeyOutputBodyFromJSON(jsonValue));
    }

    /**
     * Mint an organization API key for automation (e.g. Terraform). The plaintext token is returned once.
     */
    async createApiKey(requestParameters: CreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAPIKeyOutputBody> {
        const response = await this.createApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiKeys without sending the request
     */
    async listApiKeysRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api-keys`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the organization\'s API keys (secrets are never returned).
     */
    async listApiKeysRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAPIKeysOutputBody>> {
        const requestOptions = await this.listApiKeysRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAPIKeysOutputBodyFromJSON(jsonValue));
    }

    /**
     * List the organization\'s API keys (secrets are never returned).
     */
    async listApiKeys(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAPIKeysOutputBody> {
        const response = await this.listApiKeysRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeApiKey without sending the request
     */
    async revokeApiKeyRequestOpts(requestParameters: RevokeApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling revokeApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api-keys/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke an organization API key. Idempotent from the caller\'s view.
     */
    async revokeApiKeyRaw(requestParameters: RevokeApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.revokeApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke an organization API key. Idempotent from the caller\'s view.
     */
    async revokeApiKey(requestParameters: RevokeApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeApiKeyRaw(requestParameters, initOverrides);
    }

}
