/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AcceptInviteInputBody,
    AcceptInviteInputBodyFromJSON,
    AcceptInviteInputBodyToJSON,
} from '../models/AcceptInviteInputBody';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';
import {
    type LoginInputBody,
    LoginInputBodyFromJSON,
    LoginInputBodyToJSON,
} from '../models/LoginInputBody';
import {
    type LoginOutputBody,
    LoginOutputBodyFromJSON,
    LoginOutputBodyToJSON,
} from '../models/LoginOutputBody';
import {
    type LogoutInputBody,
    LogoutInputBodyFromJSON,
    LogoutInputBodyToJSON,
} from '../models/LogoutInputBody';
import {
    type MeOutputBody,
    MeOutputBodyFromJSON,
    MeOutputBodyToJSON,
} from '../models/MeOutputBody';
import {
    type RefreshInputBody,
    RefreshInputBodyFromJSON,
    RefreshInputBodyToJSON,
} from '../models/RefreshInputBody';
import {
    type RefreshOutputBody,
    RefreshOutputBodyFromJSON,
    RefreshOutputBodyToJSON,
} from '../models/RefreshOutputBody';
import {
    type SignupInputBody,
    SignupInputBodyFromJSON,
    SignupInputBodyToJSON,
} from '../models/SignupInputBody';
import {
    type SignupOutputBody,
    SignupOutputBodyFromJSON,
    SignupOutputBodyToJSON,
} from '../models/SignupOutputBody';
import {
    type SwitchOrgInputBody,
    SwitchOrgInputBodyFromJSON,
    SwitchOrgInputBodyToJSON,
} from '../models/SwitchOrgInputBody';
import {
    type VerifyEmailInputBody,
    VerifyEmailInputBodyFromJSON,
    VerifyEmailInputBodyToJSON,
} from '../models/VerifyEmailInputBody';

export interface AuthAcceptInviteRequest {
    acceptInviteInputBody: Omit<AcceptInviteInputBody, '$schema'>;
}

export interface AuthLoginRequest {
    loginInputBody: Omit<LoginInputBody, '$schema'>;
}

export interface AuthLogoutRequest {
    logoutInputBody: Omit<LogoutInputBody, '$schema'>;
}

export interface AuthRefreshRequest {
    refreshInputBody: Omit<RefreshInputBody, '$schema'>;
}

export interface AuthSignupRequest {
    signupInputBody: Omit<SignupInputBody, '$schema'>;
}

export interface AuthSwitchOrgRequest {
    switchOrgInputBody: Omit<SwitchOrgInputBody, '$schema'>;
}

export interface AuthVerifyEmailRequest {
    verifyEmailInputBody: Omit<VerifyEmailInputBody, '$schema'>;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authAcceptInvite without sending the request
     */
    async authAcceptInviteRequestOpts(requestParameters: AuthAcceptInviteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['acceptInviteInputBody'] == null) {
            throw new runtime.RequiredError(
                'acceptInviteInputBody',
                'Required parameter "acceptInviteInputBody" was null or undefined when calling authAcceptInvite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/accept-invite`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptInviteInputBodyToJSON(requestParameters['acceptInviteInputBody']),
        };
    }

    /**
     * Accept an organization invite: set a password (if new) and sign in to the org.
     */
    async authAcceptInviteRaw(requestParameters: AuthAcceptInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOutputBody>> {
        const requestOptions = await this.authAcceptInviteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutputBodyFromJSON(jsonValue));
    }

    /**
     * Accept an organization invite: set a password (if new) and sign in to the org.
     */
    async authAcceptInvite(requestParameters: AuthAcceptInviteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOutputBody> {
        const response = await this.authAcceptInviteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authLogin without sending the request
     */
    async authLoginRequestOpts(requestParameters: AuthLoginRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginInputBody'] == null) {
            throw new runtime.RequiredError(
                'loginInputBody',
                'Required parameter "loginInputBody" was null or undefined when calling authLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginInputBodyToJSON(requestParameters['loginInputBody']),
        };
    }

    /**
     * Exchange credentials for an access + refresh token. Returns membership list when no organization_id is given and multiple memberships exist.
     */
    async authLoginRaw(requestParameters: AuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOutputBody>> {
        const requestOptions = await this.authLoginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutputBodyFromJSON(jsonValue));
    }

    /**
     * Exchange credentials for an access + refresh token. Returns membership list when no organization_id is given and multiple memberships exist.
     */
    async authLogin(requestParameters: AuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOutputBody> {
        const response = await this.authLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authLogout without sending the request
     */
    async authLogoutRequestOpts(requestParameters: AuthLogoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['logoutInputBody'] == null) {
            throw new runtime.RequiredError(
                'logoutInputBody',
                'Required parameter "logoutInputBody" was null or undefined when calling authLogout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogoutInputBodyToJSON(requestParameters['logoutInputBody']),
        };
    }

    /**
     * Revoke the supplied refresh token\'s session. Idempotent.
     */
    async authLogoutRaw(requestParameters: AuthLogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.authLogoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke the supplied refresh token\'s session. Idempotent.
     */
    async authLogout(requestParameters: AuthLogoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authLogoutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for authMe without sending the request
     */
    async authMeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the authenticated account, its verified-or-pending emails, and its org memberships.
     */
    async authMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeOutputBody>> {
        const requestOptions = await this.authMeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeOutputBodyFromJSON(jsonValue));
    }

    /**
     * Return the authenticated account, its verified-or-pending emails, and its org memberships.
     */
    async authMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeOutputBody> {
        const response = await this.authMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authRefresh without sending the request
     */
    async authRefreshRequestOpts(requestParameters: AuthRefreshRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['refreshInputBody'] == null) {
            throw new runtime.RequiredError(
                'refreshInputBody',
                'Required parameter "refreshInputBody" was null or undefined when calling authRefresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshInputBodyToJSON(requestParameters['refreshInputBody']),
        };
    }

    /**
     * Rotate a refresh token, returning a new access + refresh pair.
     */
    async authRefreshRaw(requestParameters: AuthRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefreshOutputBody>> {
        const requestOptions = await this.authRefreshRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefreshOutputBodyFromJSON(jsonValue));
    }

    /**
     * Rotate a refresh token, returning a new access + refresh pair.
     */
    async authRefresh(requestParameters: AuthRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefreshOutputBody> {
        const response = await this.authRefreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authSignup without sending the request
     */
    async authSignupRequestOpts(requestParameters: AuthSignupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['signupInputBody'] == null) {
            throw new runtime.RequiredError(
                'signupInputBody',
                'Required parameter "signupInputBody" was null or undefined when calling authSignup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/signup`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupInputBodyToJSON(requestParameters['signupInputBody']),
        };
    }

    /**
     * Create an account, organization, and first user; enqueue tenant provisioning.
     */
    async authSignupRaw(requestParameters: AuthSignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignupOutputBody>> {
        const requestOptions = await this.authSignupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignupOutputBodyFromJSON(jsonValue));
    }

    /**
     * Create an account, organization, and first user; enqueue tenant provisioning.
     */
    async authSignup(requestParameters: AuthSignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignupOutputBody> {
        const response = await this.authSignupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authSwitchOrg without sending the request
     */
    async authSwitchOrgRequestOpts(requestParameters: AuthSwitchOrgRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['switchOrgInputBody'] == null) {
            throw new runtime.RequiredError(
                'switchOrgInputBody',
                'Required parameter "switchOrgInputBody" was null or undefined when calling authSwitchOrg().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/switch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SwitchOrgInputBodyToJSON(requestParameters['switchOrgInputBody']),
        };
    }

    /**
     * Issue a new token pair scoped to another organization the account belongs to.
     */
    async authSwitchOrgRaw(requestParameters: AuthSwitchOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginOutputBody>> {
        const requestOptions = await this.authSwitchOrgRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginOutputBodyFromJSON(jsonValue));
    }

    /**
     * Issue a new token pair scoped to another organization the account belongs to.
     */
    async authSwitchOrg(requestParameters: AuthSwitchOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginOutputBody> {
        const response = await this.authSwitchOrgRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authVerifyEmail without sending the request
     */
    async authVerifyEmailRequestOpts(requestParameters: AuthVerifyEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verifyEmailInputBody'] == null) {
            throw new runtime.RequiredError(
                'verifyEmailInputBody',
                'Required parameter "verifyEmailInputBody" was null or undefined when calling authVerifyEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/verify-email`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyEmailInputBodyToJSON(requestParameters['verifyEmailInputBody']),
        };
    }

    /**
     * Consume a verification token to mark an email address verified. Idempotent.
     */
    async authVerifyEmailRaw(requestParameters: AuthVerifyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.authVerifyEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Consume a verification token to mark an email address verified. Idempotent.
     */
    async authVerifyEmail(requestParameters: AuthVerifyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authVerifyEmailRaw(requestParameters, initOverrides);
    }

}
