/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DatacenterBody,
    DatacenterBodyFromJSON,
    DatacenterBodyToJSON,
} from '../models/DatacenterBody';
import {
    type DatacenterListOutputBody,
    DatacenterListOutputBodyFromJSON,
    DatacenterListOutputBodyToJSON,
} from '../models/DatacenterListOutputBody';
import {
    type DatacenterView,
    DatacenterViewFromJSON,
    DatacenterViewToJSON,
} from '../models/DatacenterView';
import {
    type DiscoverInputBody,
    DiscoverInputBodyFromJSON,
    DiscoverInputBodyToJSON,
} from '../models/DiscoverInputBody';
import {
    type DiscoverOutputBody,
    DiscoverOutputBodyFromJSON,
    DiscoverOutputBodyToJSON,
} from '../models/DiscoverOutputBody';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';

export interface CreateDatacenterRequest {
    datacenterBody: Omit<DatacenterBody, '$schema'>;
}

export interface DeleteDatacenterRequest {
    id: string;
}

export interface DiscoverHypervisorsRequest {
    id: string;
    discoverInputBody: Omit<DiscoverInputBody, '$schema'>;
}

export interface GetDatacenterRequest {
    id: string;
}

export interface UpdateDatacenterRequest {
    id: string;
    datacenterBody: Omit<DatacenterBody, '$schema'>;
}

/**
 * 
 */
export class DatacentersApi extends runtime.BaseAPI {

    /**
     * Creates request options for createDatacenter without sending the request
     */
    async createDatacenterRequestOpts(requestParameters: CreateDatacenterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['datacenterBody'] == null) {
            throw new runtime.RequiredError(
                'datacenterBody',
                'Required parameter "datacenterBody" was null or undefined when calling createDatacenter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DatacenterBodyToJSON(requestParameters['datacenterBody']),
        };
    }

    /**
     * Create a datacenter in the caller\'s tenant.
     */
    async createDatacenterRaw(requestParameters: CreateDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatacenterView>> {
        const requestOptions = await this.createDatacenterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatacenterViewFromJSON(jsonValue));
    }

    /**
     * Create a datacenter in the caller\'s tenant.
     */
    async createDatacenter(requestParameters: CreateDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatacenterView> {
        const response = await this.createDatacenterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteDatacenter without sending the request
     */
    async deleteDatacenterRequestOpts(requestParameters: DeleteDatacenterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDatacenter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a datacenter.
     */
    async deleteDatacenterRaw(requestParameters: DeleteDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteDatacenterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a datacenter.
     */
    async deleteDatacenter(requestParameters: DeleteDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDatacenterRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for discoverHypervisors without sending the request
     */
    async discoverHypervisorsRequestOpts(requestParameters: DiscoverHypervisorsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling discoverHypervisors().'
            );
        }

        if (requestParameters['discoverInputBody'] == null) {
            throw new runtime.RequiredError(
                'discoverInputBody',
                'Required parameter "discoverInputBody" was null or undefined when calling discoverHypervisors().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters/{id}/discover`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DiscoverInputBodyToJSON(requestParameters['discoverInputBody']),
        };
    }

    /**
     * Discover hypervisors from the datacenter\'s Proxmox cluster and upsert them (preserving reserved capacity and schedulable). Set async to run in the background.
     */
    async discoverHypervisorsRaw(requestParameters: DiscoverHypervisorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiscoverOutputBody>> {
        const requestOptions = await this.discoverHypervisorsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiscoverOutputBodyFromJSON(jsonValue));
    }

    /**
     * Discover hypervisors from the datacenter\'s Proxmox cluster and upsert them (preserving reserved capacity and schedulable). Set async to run in the background.
     */
    async discoverHypervisors(requestParameters: DiscoverHypervisorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiscoverOutputBody> {
        const response = await this.discoverHypervisorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDatacenter without sending the request
     */
    async getDatacenterRequestOpts(requestParameters: GetDatacenterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDatacenter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a datacenter by ID.
     */
    async getDatacenterRaw(requestParameters: GetDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatacenterView>> {
        const requestOptions = await this.getDatacenterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatacenterViewFromJSON(jsonValue));
    }

    /**
     * Fetch a datacenter by ID.
     */
    async getDatacenter(requestParameters: GetDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatacenterView> {
        const response = await this.getDatacenterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDatacenters without sending the request
     */
    async listDatacentersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List datacenters in the caller\'s tenant.
     */
    async listDatacentersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatacenterListOutputBody>> {
        const requestOptions = await this.listDatacentersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatacenterListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List datacenters in the caller\'s tenant.
     */
    async listDatacenters(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatacenterListOutputBody> {
        const response = await this.listDatacentersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDatacenter without sending the request
     */
    async updateDatacenterRequestOpts(requestParameters: UpdateDatacenterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateDatacenter().'
            );
        }

        if (requestParameters['datacenterBody'] == null) {
            throw new runtime.RequiredError(
                'datacenterBody',
                'Required parameter "datacenterBody" was null or undefined when calling updateDatacenter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DatacenterBodyToJSON(requestParameters['datacenterBody']),
        };
    }

    /**
     * Update a datacenter.
     */
    async updateDatacenterRaw(requestParameters: UpdateDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatacenterView>> {
        const requestOptions = await this.updateDatacenterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatacenterViewFromJSON(jsonValue));
    }

    /**
     * Update a datacenter.
     */
    async updateDatacenter(requestParameters: UpdateDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatacenterView> {
        const response = await this.updateDatacenterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
