/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DatacenterBody,
    DatacenterBodyFromJSON,
    DatacenterBodyToJSON,
} from '../models/DatacenterBody';
import {
    type DatacenterListOutputBody,
    DatacenterListOutputBodyFromJSON,
    DatacenterListOutputBodyToJSON,
} from '../models/DatacenterListOutputBody';
import {
    type DatacenterView,
    DatacenterViewFromJSON,
    DatacenterViewToJSON,
} from '../models/DatacenterView';
import {
    type DiscoverInputBody,
    DiscoverInputBodyFromJSON,
    DiscoverInputBodyToJSON,
} from '../models/DiscoverInputBody';
import {
    type DiscoverOutputBody,
    DiscoverOutputBodyFromJSON,
    DiscoverOutputBodyToJSON,
} from '../models/DiscoverOutputBody';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';
import {
    type HypervisorBody,
    HypervisorBodyFromJSON,
    HypervisorBodyToJSON,
} from '../models/HypervisorBody';
import {
    type HypervisorListOutputBody,
    HypervisorListOutputBodyFromJSON,
    HypervisorListOutputBodyToJSON,
} from '../models/HypervisorListOutputBody';
import {
    type HypervisorView,
    HypervisorViewFromJSON,
    HypervisorViewToJSON,
} from '../models/HypervisorView';
import {
    type SlotBody,
    SlotBodyFromJSON,
    SlotBodyToJSON,
} from '../models/SlotBody';
import {
    type SlotListOutputBody,
    SlotListOutputBodyFromJSON,
    SlotListOutputBodyToJSON,
} from '../models/SlotListOutputBody';
import {
    type SlotView,
    SlotViewFromJSON,
    SlotViewToJSON,
} from '../models/SlotView';

export interface CreateDatacenterRequest {
    datacenterBody: Omit<DatacenterBody, '$schema'>;
}

export interface CreateHypervisorRequest {
    hypervisorBody: Omit<HypervisorBody, '$schema'>;
}

export interface CreateSlotRequest {
    slotBody: Omit<SlotBody, '$schema'>;
}

export interface DeleteDatacenterRequest {
    id: string;
}

export interface DeleteHypervisorRequest {
    id: string;
}

export interface DeleteSlotRequest {
    id: string;
}

export interface DiscoverHypervisorsRequest {
    id: string;
    discoverInputBody: Omit<DiscoverInputBody, '$schema'>;
}

export interface GetDatacenterRequest {
    id: string;
}

export interface GetHypervisorRequest {
    id: string;
}

export interface GetSlotRequest {
    id: string;
}

export interface ListHypervisorsRequest {
    datacenterId?: string;
}

export interface UpdateDatacenterRequest {
    id: string;
    datacenterBody: Omit<DatacenterBody, '$schema'>;
}

export interface UpdateHypervisorRequest {
    id: string;
    hypervisorBody: Omit<HypervisorBody, '$schema'>;
}

export interface UpdateSlotRequest {
    id: string;
    slotBody: Omit<SlotBody, '$schema'>;
}

/**
 * 
 */
export class FleetApi extends runtime.BaseAPI {

    /**
     * Creates request options for createDatacenter without sending the request
     */
    async createDatacenterRequestOpts(requestParameters: CreateDatacenterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['datacenterBody'] == null) {
            throw new runtime.RequiredError(
                'datacenterBody',
                'Required parameter "datacenterBody" was null or undefined when calling createDatacenter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DatacenterBodyToJSON(requestParameters['datacenterBody']),
        };
    }

    /**
     * Create a datacenter in the caller\'s tenant.
     */
    async createDatacenterRaw(requestParameters: CreateDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatacenterView>> {
        const requestOptions = await this.createDatacenterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatacenterViewFromJSON(jsonValue));
    }

    /**
     * Create a datacenter in the caller\'s tenant.
     */
    async createDatacenter(requestParameters: CreateDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatacenterView> {
        const response = await this.createDatacenterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createHypervisor without sending the request
     */
    async createHypervisorRequestOpts(requestParameters: CreateHypervisorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['hypervisorBody'] == null) {
            throw new runtime.RequiredError(
                'hypervisorBody',
                'Required parameter "hypervisorBody" was null or undefined when calling createHypervisor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hypervisors`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HypervisorBodyToJSON(requestParameters['hypervisorBody']),
        };
    }

    /**
     * Create a hypervisor in the caller\'s tenant.
     */
    async createHypervisorRaw(requestParameters: CreateHypervisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HypervisorView>> {
        const requestOptions = await this.createHypervisorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HypervisorViewFromJSON(jsonValue));
    }

    /**
     * Create a hypervisor in the caller\'s tenant.
     */
    async createHypervisor(requestParameters: CreateHypervisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HypervisorView> {
        const response = await this.createHypervisorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSlot without sending the request
     */
    async createSlotRequestOpts(requestParameters: CreateSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slotBody'] == null) {
            throw new runtime.RequiredError(
                'slotBody',
                'Required parameter "slotBody" was null or undefined when calling createSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/slots`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SlotBodyToJSON(requestParameters['slotBody']),
        };
    }

    /**
     * Create a slot (t-shirt-size VM template) in the caller\'s tenant.
     */
    async createSlotRaw(requestParameters: CreateSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SlotView>> {
        const requestOptions = await this.createSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SlotViewFromJSON(jsonValue));
    }

    /**
     * Create a slot (t-shirt-size VM template) in the caller\'s tenant.
     */
    async createSlot(requestParameters: CreateSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SlotView> {
        const response = await this.createSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteDatacenter without sending the request
     */
    async deleteDatacenterRequestOpts(requestParameters: DeleteDatacenterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDatacenter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a datacenter.
     */
    async deleteDatacenterRaw(requestParameters: DeleteDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteDatacenterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a datacenter.
     */
    async deleteDatacenter(requestParameters: DeleteDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDatacenterRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteHypervisor without sending the request
     */
    async deleteHypervisorRequestOpts(requestParameters: DeleteHypervisorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteHypervisor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hypervisors/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a hypervisor.
     */
    async deleteHypervisorRaw(requestParameters: DeleteHypervisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteHypervisorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a hypervisor.
     */
    async deleteHypervisor(requestParameters: DeleteHypervisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteHypervisorRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteSlot without sending the request
     */
    async deleteSlotRequestOpts(requestParameters: DeleteSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/slots/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a slot.
     */
    async deleteSlotRaw(requestParameters: DeleteSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a slot.
     */
    async deleteSlot(requestParameters: DeleteSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSlotRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for discoverHypervisors without sending the request
     */
    async discoverHypervisorsRequestOpts(requestParameters: DiscoverHypervisorsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling discoverHypervisors().'
            );
        }

        if (requestParameters['discoverInputBody'] == null) {
            throw new runtime.RequiredError(
                'discoverInputBody',
                'Required parameter "discoverInputBody" was null or undefined when calling discoverHypervisors().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters/{id}/discover`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DiscoverInputBodyToJSON(requestParameters['discoverInputBody']),
        };
    }

    /**
     * Discover hypervisors from the datacenter\'s Proxmox cluster and upsert them (preserving reserved capacity and schedulable). Set async to run in the background.
     */
    async discoverHypervisorsRaw(requestParameters: DiscoverHypervisorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DiscoverOutputBody>> {
        const requestOptions = await this.discoverHypervisorsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DiscoverOutputBodyFromJSON(jsonValue));
    }

    /**
     * Discover hypervisors from the datacenter\'s Proxmox cluster and upsert them (preserving reserved capacity and schedulable). Set async to run in the background.
     */
    async discoverHypervisors(requestParameters: DiscoverHypervisorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DiscoverOutputBody> {
        const response = await this.discoverHypervisorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDatacenter without sending the request
     */
    async getDatacenterRequestOpts(requestParameters: GetDatacenterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDatacenter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a datacenter by ID.
     */
    async getDatacenterRaw(requestParameters: GetDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatacenterView>> {
        const requestOptions = await this.getDatacenterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatacenterViewFromJSON(jsonValue));
    }

    /**
     * Fetch a datacenter by ID.
     */
    async getDatacenter(requestParameters: GetDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatacenterView> {
        const response = await this.getDatacenterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getHypervisor without sending the request
     */
    async getHypervisorRequestOpts(requestParameters: GetHypervisorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getHypervisor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hypervisors/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a hypervisor by ID.
     */
    async getHypervisorRaw(requestParameters: GetHypervisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HypervisorView>> {
        const requestOptions = await this.getHypervisorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HypervisorViewFromJSON(jsonValue));
    }

    /**
     * Fetch a hypervisor by ID.
     */
    async getHypervisor(requestParameters: GetHypervisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HypervisorView> {
        const response = await this.getHypervisorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSlot without sending the request
     */
    async getSlotRequestOpts(requestParameters: GetSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/slots/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a slot by ID.
     */
    async getSlotRaw(requestParameters: GetSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SlotView>> {
        const requestOptions = await this.getSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SlotViewFromJSON(jsonValue));
    }

    /**
     * Fetch a slot by ID.
     */
    async getSlot(requestParameters: GetSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SlotView> {
        const response = await this.getSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDatacenters without sending the request
     */
    async listDatacentersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List datacenters in the caller\'s tenant.
     */
    async listDatacentersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatacenterListOutputBody>> {
        const requestOptions = await this.listDatacentersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatacenterListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List datacenters in the caller\'s tenant.
     */
    async listDatacenters(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatacenterListOutputBody> {
        const response = await this.listDatacentersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listHypervisors without sending the request
     */
    async listHypervisorsRequestOpts(requestParameters: ListHypervisorsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['datacenterId'] != null) {
            queryParameters['datacenter_id'] = requestParameters['datacenterId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hypervisors`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List hypervisors in the caller\'s tenant.
     */
    async listHypervisorsRaw(requestParameters: ListHypervisorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HypervisorListOutputBody>> {
        const requestOptions = await this.listHypervisorsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HypervisorListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List hypervisors in the caller\'s tenant.
     */
    async listHypervisors(requestParameters: ListHypervisorsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HypervisorListOutputBody> {
        const response = await this.listHypervisorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSlots without sending the request
     */
    async listSlotsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/slots`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List slots in the caller\'s tenant.
     */
    async listSlotsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SlotListOutputBody>> {
        const requestOptions = await this.listSlotsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SlotListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List slots in the caller\'s tenant.
     */
    async listSlots(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SlotListOutputBody> {
        const response = await this.listSlotsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateDatacenter without sending the request
     */
    async updateDatacenterRequestOpts(requestParameters: UpdateDatacenterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateDatacenter().'
            );
        }

        if (requestParameters['datacenterBody'] == null) {
            throw new runtime.RequiredError(
                'datacenterBody',
                'Required parameter "datacenterBody" was null or undefined when calling updateDatacenter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/datacenters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: DatacenterBodyToJSON(requestParameters['datacenterBody']),
        };
    }

    /**
     * Update a datacenter.
     */
    async updateDatacenterRaw(requestParameters: UpdateDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DatacenterView>> {
        const requestOptions = await this.updateDatacenterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DatacenterViewFromJSON(jsonValue));
    }

    /**
     * Update a datacenter.
     */
    async updateDatacenter(requestParameters: UpdateDatacenterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DatacenterView> {
        const response = await this.updateDatacenterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateHypervisor without sending the request
     */
    async updateHypervisorRequestOpts(requestParameters: UpdateHypervisorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateHypervisor().'
            );
        }

        if (requestParameters['hypervisorBody'] == null) {
            throw new runtime.RequiredError(
                'hypervisorBody',
                'Required parameter "hypervisorBody" was null or undefined when calling updateHypervisor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/hypervisors/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: HypervisorBodyToJSON(requestParameters['hypervisorBody']),
        };
    }

    /**
     * Update a hypervisor.
     */
    async updateHypervisorRaw(requestParameters: UpdateHypervisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HypervisorView>> {
        const requestOptions = await this.updateHypervisorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HypervisorViewFromJSON(jsonValue));
    }

    /**
     * Update a hypervisor.
     */
    async updateHypervisor(requestParameters: UpdateHypervisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HypervisorView> {
        const response = await this.updateHypervisorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSlot without sending the request
     */
    async updateSlotRequestOpts(requestParameters: UpdateSlotRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSlot().'
            );
        }

        if (requestParameters['slotBody'] == null) {
            throw new runtime.RequiredError(
                'slotBody',
                'Required parameter "slotBody" was null or undefined when calling updateSlot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/slots/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SlotBodyToJSON(requestParameters['slotBody']),
        };
    }

    /**
     * Update a slot.
     */
    async updateSlotRaw(requestParameters: UpdateSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SlotView>> {
        const requestOptions = await this.updateSlotRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SlotViewFromJSON(jsonValue));
    }

    /**
     * Update a slot.
     */
    async updateSlot(requestParameters: UpdateSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SlotView> {
        const response = await this.updateSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
