/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AddMemberInputBody,
    AddMemberInputBodyFromJSON,
    AddMemberInputBodyToJSON,
} from '../models/AddMemberInputBody';
import {
    type AddMemberOutputBody,
    AddMemberOutputBodyFromJSON,
    AddMemberOutputBodyToJSON,
} from '../models/AddMemberOutputBody';
import {
    type CreateOrgInputBody,
    CreateOrgInputBodyFromJSON,
    CreateOrgInputBodyToJSON,
} from '../models/CreateOrgInputBody';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';
import {
    type MemberJSONView,
    MemberJSONViewFromJSON,
    MemberJSONViewToJSON,
} from '../models/MemberJSONView';
import {
    type MemberListOutputBody,
    MemberListOutputBodyFromJSON,
    MemberListOutputBodyToJSON,
} from '../models/MemberListOutputBody';
import {
    type OrgFullView,
    OrgFullViewFromJSON,
    OrgFullViewToJSON,
} from '../models/OrgFullView';
import {
    type OrgListOutputBody,
    OrgListOutputBodyFromJSON,
    OrgListOutputBodyToJSON,
} from '../models/OrgListOutputBody';
import {
    type UpdateMemberInputBody,
    UpdateMemberInputBodyFromJSON,
    UpdateMemberInputBodyToJSON,
} from '../models/UpdateMemberInputBody';
import {
    type UpdateOrgInputBody,
    UpdateOrgInputBodyFromJSON,
    UpdateOrgInputBodyToJSON,
} from '../models/UpdateOrgInputBody';

export interface AddMemberRequest {
    id: string;
    addMemberInputBody: Omit<AddMemberInputBody, '$schema'>;
}

export interface CreateOrgRequest {
    createOrgInputBody: Omit<CreateOrgInputBody, '$schema'>;
}

export interface DeleteOrgRequest {
    id: string;
}

export interface GetOrgRequest {
    id: string;
}

export interface ListMembersRequest {
    id: string;
}

export interface RemoveMemberRequest {
    id: string;
    userId: string;
}

export interface UpdateMemberRequest {
    id: string;
    userId: string;
    updateMemberInputBody: Omit<UpdateMemberInputBody, '$schema'>;
}

export interface UpdateOrgRequest {
    id: string;
    updateOrgInputBody: Omit<UpdateOrgInputBody, '$schema'>;
}

/**
 * 
 */
export class OrganizationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for addMember without sending the request
     */
    async addMemberRequestOpts(requestParameters: AddMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addMember().'
            );
        }

        if (requestParameters['addMemberInputBody'] == null) {
            throw new runtime.RequiredError(
                'addMemberInputBody',
                'Required parameter "addMemberInputBody" was null or undefined when calling addMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{id}/members`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddMemberInputBodyToJSON(requestParameters['addMemberInputBody']),
        };
    }

    /**
     * Add or invite a member by email (admin+; owner required to grant owner). Unknown emails get an invite link.
     */
    async addMemberRaw(requestParameters: AddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddMemberOutputBody>> {
        const requestOptions = await this.addMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddMemberOutputBodyFromJSON(jsonValue));
    }

    /**
     * Add or invite a member by email (admin+; owner required to grant owner). Unknown emails get an invite link.
     */
    async addMember(requestParameters: AddMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddMemberOutputBody> {
        const response = await this.addMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createOrg without sending the request
     */
    async createOrgRequestOpts(requestParameters: CreateOrgRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createOrgInputBody'] == null) {
            throw new runtime.RequiredError(
                'createOrgInputBody',
                'Required parameter "createOrgInputBody" was null or undefined when calling createOrg().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrgInputBodyToJSON(requestParameters['createOrgInputBody']),
        };
    }

    /**
     * Create an organization (you become its owner) and enqueue tenant provisioning.
     */
    async createOrgRaw(requestParameters: CreateOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgFullView>> {
        const requestOptions = await this.createOrgRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgFullViewFromJSON(jsonValue));
    }

    /**
     * Create an organization (you become its owner) and enqueue tenant provisioning.
     */
    async createOrg(requestParameters: CreateOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgFullView> {
        const response = await this.createOrgRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteOrg without sending the request
     */
    async deleteOrgRequestOpts(requestParameters: DeleteOrgRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteOrg().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an organization and enqueue tenant teardown (owner only).
     */
    async deleteOrgRaw(requestParameters: DeleteOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteOrgRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an organization and enqueue tenant teardown (owner only).
     */
    async deleteOrg(requestParameters: DeleteOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrgRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getOrg without sending the request
     */
    async getOrgRequestOpts(requestParameters: GetOrgRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOrg().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get an organization the caller belongs to.
     */
    async getOrgRaw(requestParameters: GetOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgFullView>> {
        const requestOptions = await this.getOrgRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgFullViewFromJSON(jsonValue));
    }

    /**
     * Get an organization the caller belongs to.
     */
    async getOrg(requestParameters: GetOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgFullView> {
        const response = await this.getOrgRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMembers without sending the request
     */
    async listMembersRequestOpts(requestParameters: ListMembersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{id}/members`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List an organization\'s members.
     */
    async listMembersRaw(requestParameters: ListMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberListOutputBody>> {
        const requestOptions = await this.listMembersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List an organization\'s members.
     */
    async listMembers(requestParameters: ListMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberListOutputBody> {
        const response = await this.listMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrgs without sending the request
     */
    async listOrgsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the organizations the caller belongs to (with their role).
     */
    async listOrgsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgListOutputBody>> {
        const requestOptions = await this.listOrgsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List the organizations the caller belongs to (with their role).
     */
    async listOrgs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgListOutputBody> {
        const response = await this.listOrgsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeMember without sending the request
     */
    async removeMemberRequestOpts(requestParameters: RemoveMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeMember().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{id}/members/{userId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a member (admin+; owner required to remove owners; never the last owner).
     */
    async removeMemberRaw(requestParameters: RemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.removeMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a member (admin+; owner required to remove owners; never the last owner).
     */
    async removeMember(requestParameters: RemoveMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeMemberRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateMember without sending the request
     */
    async updateMemberRequestOpts(requestParameters: UpdateMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateMember().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling updateMember().'
            );
        }

        if (requestParameters['updateMemberInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateMemberInputBody',
                'Required parameter "updateMemberInputBody" was null or undefined when calling updateMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{id}/members/{userId}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMemberInputBodyToJSON(requestParameters['updateMemberInputBody']),
        };
    }

    /**
     * Change a member\'s role (admin+; owner required to touch owners).
     */
    async updateMemberRaw(requestParameters: UpdateMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberJSONView>> {
        const requestOptions = await this.updateMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberJSONViewFromJSON(jsonValue));
    }

    /**
     * Change a member\'s role (admin+; owner required to touch owners).
     */
    async updateMember(requestParameters: UpdateMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberJSONView> {
        const response = await this.updateMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateOrg without sending the request
     */
    async updateOrgRequestOpts(requestParameters: UpdateOrgRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateOrg().'
            );
        }

        if (requestParameters['updateOrgInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateOrgInputBody',
                'Required parameter "updateOrgInputBody" was null or undefined when calling updateOrg().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/organizations/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrgInputBodyToJSON(requestParameters['updateOrgInputBody']),
        };
    }

    /**
     * Rename an organization (admin or owner).
     */
    async updateOrgRaw(requestParameters: UpdateOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrgFullView>> {
        const requestOptions = await this.updateOrgRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrgFullViewFromJSON(jsonValue));
    }

    /**
     * Rename an organization (admin or owner).
     */
    async updateOrg(requestParameters: UpdateOrgRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrgFullView> {
        const response = await this.updateOrgRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
