/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BackfillVMIDInputBody,
    BackfillVMIDInputBodyFromJSON,
    BackfillVMIDInputBodyToJSON,
} from '../models/BackfillVMIDInputBody';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';
import {
    type FleetPlacementListOutputBody,
    FleetPlacementListOutputBodyFromJSON,
    FleetPlacementListOutputBodyToJSON,
} from '../models/FleetPlacementListOutputBody';
import {
    type PlacementView,
    PlacementViewFromJSON,
    PlacementViewToJSON,
} from '../models/PlacementView';

export interface BackfillPlacementVmidRequest {
    id: string;
    backfillVMIDInputBody: Omit<BackfillVMIDInputBody, '$schema'>;
}

/**
 * 
 */
export class PlacementApi extends runtime.BaseAPI {

    /**
     * Creates request options for backfillPlacementVmid without sending the request
     */
    async backfillPlacementVmidRequestOpts(requestParameters: BackfillPlacementVmidRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling backfillPlacementVmid().'
            );
        }

        if (requestParameters['backfillVMIDInputBody'] == null) {
            throw new runtime.RequiredError(
                'backfillVMIDInputBody',
                'Required parameter "backfillVMIDInputBody" was null or undefined when calling backfillPlacementVmid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/placements/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BackfillVMIDInputBodyToJSON(requestParameters['backfillVMIDInputBody']),
        };
    }

    /**
     * Attach the externally-assigned Proxmox vmid to a placement.
     */
    async backfillPlacementVmidRaw(requestParameters: BackfillPlacementVmidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlacementView>> {
        const requestOptions = await this.backfillPlacementVmidRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlacementViewFromJSON(jsonValue));
    }

    /**
     * Attach the externally-assigned Proxmox vmid to a placement.
     */
    async backfillPlacementVmid(requestParameters: BackfillPlacementVmidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlacementView> {
        const response = await this.backfillPlacementVmidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPlacements without sending the request
     */
    async listPlacementsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/placements`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all placements in the tenant with pool, slot, and hypervisor context (fleet overview).
     */
    async listPlacementsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FleetPlacementListOutputBody>> {
        const requestOptions = await this.listPlacementsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FleetPlacementListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List all placements in the tenant with pool, slot, and hypervisor context (fleet overview).
     */
    async listPlacements(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FleetPlacementListOutputBody> {
        const response = await this.listPlacementsRaw(initOverrides);
        return await response.value();
    }

}
