/* tslint:disable */
/* eslint-disable */
/**
 * Waggle
 * Waggle API.
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreatePoolInputBody,
    CreatePoolInputBodyFromJSON,
    CreatePoolInputBodyToJSON,
} from '../models/CreatePoolInputBody';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';
import {
    type PlacementListOutputBody,
    PlacementListOutputBodyFromJSON,
    PlacementListOutputBodyToJSON,
} from '../models/PlacementListOutputBody';
import {
    type PoolListOutputBody,
    PoolListOutputBodyFromJSON,
    PoolListOutputBodyToJSON,
} from '../models/PoolListOutputBody';
import {
    type PoolView,
    PoolViewFromJSON,
    PoolViewToJSON,
} from '../models/PoolView';
import {
    type ResizePoolInputBody,
    ResizePoolInputBodyFromJSON,
    ResizePoolInputBodyToJSON,
} from '../models/ResizePoolInputBody';

export interface CreatePoolRequest {
    createPoolInputBody: Omit<CreatePoolInputBody, '$schema'>;
}

export interface DeletePoolRequest {
    id: string;
}

export interface GetPoolRequest {
    id: string;
}

export interface ListPoolPlacementsRequest {
    id: string;
}

export interface ResizePoolRequest {
    id: string;
    resizePoolInputBody: Omit<ResizePoolInputBody, '$schema'>;
}

/**
 * 
 */
export class PoolsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPool without sending the request
     */
    async createPoolRequestOpts(requestParameters: CreatePoolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createPoolInputBody'] == null) {
            throw new runtime.RequiredError(
                'createPoolInputBody',
                'Required parameter "createPoolInputBody" was null or undefined when calling createPool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pools`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePoolInputBodyToJSON(requestParameters['createPoolInputBody']),
        };
    }

    /**
     * Create a node pool and place its VMs across hypervisors (anti-affinity spread, all-or-nothing). Placements are available at GET /pools/{id}/placements.
     */
    async createPoolRaw(requestParameters: CreatePoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PoolView>> {
        const requestOptions = await this.createPoolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PoolViewFromJSON(jsonValue));
    }

    /**
     * Create a node pool and place its VMs across hypervisors (anti-affinity spread, all-or-nothing). Placements are available at GET /pools/{id}/placements.
     */
    async createPool(requestParameters: CreatePoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PoolView> {
        const response = await this.createPoolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePool without sending the request
     */
    async deletePoolRequestOpts(requestParameters: DeletePoolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pools/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a pool and release all its placements.
     */
    async deletePoolRaw(requestParameters: DeletePoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePoolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a pool and release all its placements.
     */
    async deletePool(requestParameters: DeletePoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePoolRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getPool without sending the request
     */
    async getPoolRequestOpts(requestParameters: GetPoolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pools/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch a pool. Its placements are available at GET /pools/{id}/placements.
     */
    async getPoolRaw(requestParameters: GetPoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PoolView>> {
        const requestOptions = await this.getPoolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PoolViewFromJSON(jsonValue));
    }

    /**
     * Fetch a pool. Its placements are available at GET /pools/{id}/placements.
     */
    async getPool(requestParameters: GetPoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PoolView> {
        const response = await this.getPoolRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPoolPlacements without sending the request
     */
    async listPoolPlacementsRequestOpts(requestParameters: ListPoolPlacementsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listPoolPlacements().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pools/{id}/placements`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List a pool\'s placements (hypervisor + optional vmid).
     */
    async listPoolPlacementsRaw(requestParameters: ListPoolPlacementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlacementListOutputBody>> {
        const requestOptions = await this.listPoolPlacementsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlacementListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List a pool\'s placements (hypervisor + optional vmid).
     */
    async listPoolPlacements(requestParameters: ListPoolPlacementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlacementListOutputBody> {
        const response = await this.listPoolPlacementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPools without sending the request
     */
    async listPoolsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pools`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List node pools in the caller\'s tenant.
     */
    async listPoolsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PoolListOutputBody>> {
        const requestOptions = await this.listPoolsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PoolListOutputBodyFromJSON(jsonValue));
    }

    /**
     * List node pools in the caller\'s tenant.
     */
    async listPools(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PoolListOutputBody> {
        const response = await this.listPoolsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resizePool without sending the request
     */
    async resizePoolRequestOpts(requestParameters: ResizePoolRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resizePool().'
            );
        }

        if (requestParameters['resizePoolInputBody'] == null) {
            throw new runtime.RequiredError(
                'resizePoolInputBody',
                'Required parameter "resizePoolInputBody" was null or undefined when calling resizePool().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pools/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ResizePoolInputBodyToJSON(requestParameters['resizePoolInputBody']),
        };
    }

    /**
     * Resize a pool\'s desired count. Grow places new VMs (all-or-nothing); shrink removes newest placements (LIFO). Placements are available at GET /pools/{id}/placements.
     */
    async resizePoolRaw(requestParameters: ResizePoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PoolView>> {
        const requestOptions = await this.resizePoolRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PoolViewFromJSON(jsonValue));
    }

    /**
     * Resize a pool\'s desired count. Grow places new VMs (all-or-nothing); shrink removes newest placements (LIFO). Placements are available at GET /pools/{id}/placements.
     */
    async resizePool(requestParameters: ResizePoolRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PoolView> {
        const response = await this.resizePoolRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
