// Code generated by waggle. DO NOT EDIT.
//
// Hand-authored regression tests for the generated Terraform provider client,
// injected after each `waggle generate terraform openapi-generator` run. They
// guard two generator patches that have no other test: patchClientReadOnlyOmitempty
// and patchTerraformAPIKeyBearer. They live here rather than in the provider
// repo because internal/client is replaced wholesale on every regenerate.
// Edit the source at cmd/overlays/client_body_test.go.tmpl in the waggle repo.
package client

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// Create/update bodies are built from the response view models; read-only,
// server-assigned fields must be omitted so the strict API doesn't 422.
func TestCreateBodyOmitsReadOnlyFields(t *testing.T) {
	b, err := json.Marshal(SlotView{Name: "small", Vcpu: 2, RamGb: 8, DiskGb: 40})
	if err != nil {
		t.Fatal(err)
	}
	body := string(b)
	for _, f := range []string{"id", "created_at", "updated_at", "$schema"} {
		if strings.Contains(body, `"`+f+`"`) {
			t.Errorf("request body must omit read-only field %q; got %s", f, body)
		}
	}
	for _, f := range []string{"name", "vcpu", "ram_gb", "disk_gb"} {
		if !strings.Contains(body, `"`+f+`"`) {
			t.Errorf("request body must include writable field %q; got %s", f, body)
		}
	}
}

// The org API key must be sent as a Bearer token (the API's only auth scheme).
func TestApiKeySentAsBearer(t *testing.T) {
	var got string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("Authorization")
		_, _ = w.Write([]byte("{}"))
	}))
	defer srv.Close()

	c := NewClient(srv.URL)
	c.ApiKey = "wgl_test"
	if _, err := c.DoRequest(context.Background(), "GET", "/x", nil); err != nil {
		t.Fatal(err)
	}
	if got != "Bearer wgl_test" {
		t.Errorf(`Authorization = %q, want "Bearer wgl_test"`, got)
	}
}
