// Code generated by waggle. DO NOT EDIT.
//
// Hand-authored Terraform data source injected into the generated provider
// after each `waggle generate terraform openapi-generator` run. The OpenAPI
// Generator cannot model the placements list (a list of nested objects), so
// this is maintained by hand. Edit the source at
// cmd/overlays/pool_placements_data_source.go.tmpl in the waggle repo.
package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/glueops/terraform-provider-waggle/internal/client"
)

var _ datasource.DataSource = &PoolPlacementsDataSource{}

func NewPoolPlacementsDataSource() datasource.DataSource {
	return &PoolPlacementsDataSource{}
}

type PoolPlacementsDataSource struct {
	client *client.Client
}

type poolPlacementsModel struct {
	PoolID     types.String           `tfsdk:"pool_id"`
	Placements []poolPlacementElement `tfsdk:"placements"`
}

type poolPlacementElement struct {
	ID             types.String `tfsdk:"id"`
	HypervisorID   types.String `tfsdk:"hypervisor_id"`
	HypervisorName types.String `tfsdk:"hypervisor_name"`
	Vmid           types.Int64  `tfsdk:"vmid"`
	CreatedAt      types.String `tfsdk:"created_at"`
}

func (d *PoolPlacementsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pool_placements"
}

func (d *PoolPlacementsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Placements Waggle computed for a pool: which hypervisor and vmid each VM should use.",
		Attributes: map[string]schema.Attribute{
			"pool_id": schema.StringAttribute{
				Required:    true,
				Description: "ID of the pool whose placements to fetch.",
			},
			"placements": schema.ListNestedAttribute{
				Computed:    true,
				Description: "Placements for the pool, one element per VM.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:    true,
							Description: "Placement ID.",
						},
						"hypervisor_id": schema.StringAttribute{
							Computed:    true,
							Description: "Target hypervisor ID.",
						},
						"hypervisor_name": schema.StringAttribute{
							Computed:    true,
							Description: "Target hypervisor name (the Proxmox node to create the VM on).",
						},
						"vmid": schema.Int64Attribute{
							Computed:    true,
							Description: "Reserved Proxmox vmid for the VM; null until assigned.",
						},
						"created_at": schema.StringAttribute{
							Computed:    true,
							Description: "Placement creation timestamp.",
						},
					},
				},
			},
		},
	}
}

func (d *PoolPlacementsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *PoolPlacementsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config poolPlacementsModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/pools/%v/placements", config.PoolID.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading pool placements", err.Error())
		return
	}

	// placementListOutput: { "items": [ { id, hypervisor_id, hypervisor_name, vmid, created_at } ] }
	var result struct {
		Items []struct {
			ID             string `json:"id"`
			HypervisorID   string `json:"hypervisor_id"`
			HypervisorName string `json:"hypervisor_name"`
			Vmid           *int64 `json:"vmid"`
			CreatedAt      string `json:"created_at"`
		} `json:"items"`
	}
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.Placements = make([]poolPlacementElement, 0, len(result.Items))
	for _, it := range result.Items {
		elem := poolPlacementElement{
			ID:             types.StringValue(it.ID),
			HypervisorID:   types.StringValue(it.HypervisorID),
			HypervisorName: types.StringValue(it.HypervisorName),
			CreatedAt:      types.StringValue(it.CreatedAt),
			Vmid:           types.Int64Null(),
		}
		if it.Vmid != nil {
			elem.Vmid = types.Int64Value(*it.Vmid)
		}
		config.Placements = append(config.Placements, elem)
	}

	tflog.Trace(ctx, "read pool placements data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
