import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // src/sdk is Hey API output, regenerated by `just sdk`. Linting it only
  // produces churn that cannot be fixed here, since the next generation
  // overwrites any edit.
  globalIgnores(['dist', 'src/sdk']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // Fast refresh wants one component per module. Two established patterns
      // in this codebase legitimately break that, and neither is a bug:
      //   - shadcn/ui components re-export their cva variants next to the
      //     component (`export { Button, buttonVariants }`). allowConstantExport
      //     does not cover re-exports, so these are named explicitly.
      //   - context hooks live beside their provider (useTheme, useAuth).
      // Anything else exporting non-components still fails.
      'react-refresh/only-export-components': [
        'error',
        {
          allowConstantExport: true,
          allowExportNames: [
            'useTheme',
            'useAuth',
            'badgeVariants',
            'buttonVariants',
          ],
        },
      ],
    },
  },
])
